### ISSUE TITLE
tensorflow tile inconsistent with other tensorlibs

### ISSUE THREAD

**Issue by kratsg** [scikit-hep/pyhf#1025]
Demonstrated rather simply below:

```python
>>> import pyhf
>>> pyhf.tensorlib.tile(pyhf.tensorlib.astensor([1.]), (2, 1))
array([[1.],
       [1.]])

>>> pyhf.set_backend('jax')
>>> pyhf.tensorlib.tile(pyhf.tensorlib.astensor([1.]), (2, 1))

>>> pyhf.set_backend('pytorch')
>>> pyhf.tensorlib.tile(pyhf.tensorlib.astensor([1.]), (2, 1))
tensor([[1.],
        [1.]])

>>> pyhf.set_backend('tensorflow')
>>> pyhf.tensorlib.tile(pyhf.tensorlib.astensor([1.]), (2, 1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kratsg/.virtualenvs/pyhf/lib/python3.7/site-packages/pyhf/tensor/tensorflow_backend.py", line 78, in tile
    return tf.tile(tensor_in, repeats)
  File "/Users/kratsg/.virtualenvs/pyhf/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 11393, in tile
    input, multiples, name=name, ctx=_ctx)
  File "/Users/kratsg/.virtualenvs/pyhf/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 11433, in tile_eager_fallback
    ctx=ctx, name=name)
  File "/Users/kratsg/.virtualenvs/pyhf/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expected multiples argument to be a vector of length 1 but got length 2 [Op:Tile]
```

**Comment by matthewfeickert** [comment]
Should we get this addressed _before_ PR #731 goes in? I'm a bit hesitant to specifically add test cases that treat backends different (one of the reasons PR #817 is taking _forever_ to be ready).
