### ISSUE TITLE
BkgOnly.json file of SUSY-2018-06 analysis giving obs==exp CLs

### ISSUE THREAD

**Issue by sabinekraml** [scikit-hep/pyhf#1032]
As noted by Gael in #620, when using the background-only workspace 'BkgOnly.json' file of the SUSY-2018-06 analysis (3L EW-ino search) from HEPData in SModelS, hypotest seems to always return the same expected and observed CLs. Any idea how this arises? Is it a bug in the json fnile or in our usage of it?

**Comment by matthewfeickert** [comment]
@sabinekraml @Ga0l Can you please provide reproducible code that demonstrates this?

**Comment by matthewfeickert** [comment]
Hm. Okay, so the following Shell script (`example.sh`)

```bash
#!/usr/bin/env bash

function cls_patch() {
  #1: model mass 1
  #2: model mass 2
  local mass1
  local mass2
  mass1="${1}"
  mass2="${2}"
  printf "\nmodel: %s, %s\n" "${mass1}" "${mass2}"
  pyhf cls --backend pytorch BkgOnly.json -p "patch.ERJR_${mass1}p0_${mass2}p0.json"
}

# signal patchset for the SUSY 3L EW-ino analysis
if [[ ! -d 3L-likelihoods ]]; then
  curl -sL --location --output "$PWD/3L-likelihoods.tar.gz" https://www.hepdata.net/record/resource/1165724?view=true
  tar -xvf 3L-likelihoods.tar.gz --one-top-level
fi
cd 3L-likelihoods || exit

cls_patch 250 150
cls_patch 300 150
cls_patch 450 150

cls_patch 100 60
cls_patch 500 300 
```

evaluates

```
$ bash example.sh
```

the patches as

```
model: 250, 150
{
    "CLs_exp": [
        0.9988126719402587,
        0.9992367784999728,
        0.9996006157073914,
        0.99985600465414,
        0.9999723316152318
    ],
    "CLs_obs": 0.9996007606784533
}

model: 300, 150
{
    "CLs_exp": [
        0.9987863406468523,
        0.9992198482575744,
        0.9995917540558055,
        0.9998528088272489,
        0.9999717173871188
    ],
    "CLs_obs": 0.9995919054143043
}

model: 450, 150
{
    "CLs_exp": [
        0.9999419836173645,
        0.9999627156016401,
        0.9999804941831012,
        0.999992968981703,
        0.999998649327118
    ],
    "CLs_obs": 0.9999804942382481
}

model: 100, 60
{
    "CLs_exp": [
        0.9996712260318957,
        0.9997887003910872,
        0.9998894495601849,
        0.9999601489895122,
        0.9999923441032177
    ],
    "CLs_obs": 0.9998894614209197
}

model: 500, 300
{
    "CLs_exp": [
        0.9999638191128344,
        0.9999767483537789,
        0.9999878356554701,
        0.9999956152907656,
        0.9999991576923339
    ],
    "CLs_obs": 0.9999878356904083
}
```

I wasn't involved with this analysis, so maybe we can follow up more on this with @kratsg and the others that did. (Off topic, but I didn't realize until I went to look at this that this was pre-patchset. Is it possible to reupload the likelihoods for older analyses as patchsets? Or does that break things for HEPData?)

**Comment by matthewfeickert** [comment]
@sabinekraml @Ga0l Oh, I think after looking at things more closely I understand.

```
$ cd 3L-likelihoods
$ tail -4 README.md 

# Known Issues

These workspaces are the first time that multiple fixed parameters exist in the measurement definition. If using pyhf, take note of this issue [scikit-hep/pyhf#739](https://github.com/scikit-hep/pyhf/issues/739) which will be resolved shortly after these likelihoods are public.
```

And as it says if you check Issue #739 we discuss this. So @kratsg and I think that we just need to get PR #846 in to resolve this.

**Comment by Ga0l** [comment]
Hi,

Congrats for the new release! I just tested your [example.sh](https://github.com/scikit-hep/pyhf/issues/1032#issuecomment-675161561) with pyhfv-0.5.2. Observed and expected CLs are still very close for the SUSY-2018-06 analysis (3L EW-ino search), is that the same for you?
Actually, I don't really understand the usage of the argument `fixed_params` in `hypotest`.

Thanks for your help!

**Comment by kratsg** [comment]
Hi @Ga0l , can you confirm which optimizer you're using? It does certainly seem to be an issue that perhaps the scipy optimizer is not able to minimize this workspace succesfully.

I picked the `ERJR_300p0_100p0` point here:

```
$ pyhf cls ~/Downloads/likelihoods/BkgOnly.json --patch <(pyhf patchset extract ~/Downloads/likelihoods/patchset.json --name ERJR_300p0_100p0)
/Users/kratsg/.virtualenvs/pyhf/lib/python3.7/site-packages/pyhf/tensor/numpy_backend.py:271: RuntimeWarning: invalid value encountered in log
  return n * np.log(lam) - lam - gammaln(n + 1.0)
{
    "CLs_exp": [
        0.9987474975959262,
        0.9991948729820783,
        0.9995786812818501,
        0.9998480942549817,
        0.9999708112483539
    ],
    "CLs_obs": 0.999576563194346
}
```

and with minuit

```
$ pyhf cls ~/Downloads/likelihoods/BkgOnly.json --patch <(pyhf patchset extract ~/Downloads/likelihoods/patchset.json --name ERJR_300p0_100p0) --optimizer minuit_optimizer
{
    "CLs_exp": [
        1.1507866646947804e-05,
        0.00018540403348994429,
        0.0025490884892843753,
        0.025939602236692196,
        0.1580650710822157
    ],
    "CLs_obs": 0.01813368764704786
}
```

> Actually, I don't really understand the usage of the argument `fixed_params` in `hypotest`.

This is following the `minuit` API more than the `scipy` API. There are an arbitrary number of nuisance parameters in the model. The model configuration will specify which of them are fixed `fixed_pars = model.config.suggested_fixed()` which is just a boolean of `True`/`False` for each NP. If a parameter is fixed, it will be fixed at the `init_par` value.

**Comment by Ga0l** [comment]
I was using the default optimizer which I guess is `scipy` and `pytorch` as backend. I tried changing the optimizer to `minuit` and it seems that `minuit` isn't compatible with the `pytorch` backend. I also tried :
```
pyhf cls 3L-likelihoods/BkgOnly.json --patch <(pyhf patchset extract 3L-likelihoods/patchset.json --name ERJR_300p0_100p0) --optimizer minuit_optimizer --backend pytorch
```
which gives :
```
ERROR:pyhf.optimize.mixins:      fun: 302.5155275307401
 hess_inv: array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])
  message: 'Optimization failed. Estimated distance to minimum too large.'
   minuit: <iminuit._libiminuit.Minuit object at 0x55801a698af0>
     nfev: 100002
     njev: 8115
  success: False
      unc: None
        x: array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1.,
       1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0.,
       1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1.,
       1.])
Traceback (most recent call last):
  File "/home/alguero/.local/lib/python3.7/site-packages/pyhf/optimize/mixins.py", line 49, in _internal_minimize
    assert result.success
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alguero/.local/bin/pyhf", line 10, in <module>
    sys.exit(cli())
  File "/home/alguero/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/alguero/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/alguero/.local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/alguero/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/alguero/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/alguero/.local/lib/python3.7/site-packages/pyhf/cli/infer.py", line 107, in cls
    testpoi, ws.data(model), model, qtilde=is_qtilde, return_expected_set=True
  File "/home/alguero/.local/lib/python3.7/site-packages/pyhf/infer/__init__.py", line 134, in hypotest
    teststat = calc.teststatistic(poi_test)
  File "/home/alguero/.local/lib/python3.7/site-packages/pyhf/infer/calculators.py", line 195, in teststatistic
    self.fixed_params,
  File "/home/alguero/.local/lib/python3.7/site-packages/pyhf/infer/test_statistics.py", line 177, in qmu_tilde
    return _qmu_like(mu, data, pdf, init_pars, par_bounds, fixed_params)
  File "/home/alguero/.local/lib/python3.7/site-packages/pyhf/infer/test_statistics.py", line 20, in _qmu_like
    mu, data, pdf, init_pars, par_bounds, fixed_params, return_fitted_pars=True
  File "/home/alguero/.local/lib/python3.7/site-packages/pyhf/infer/test_statistics.py", line 39, in _tmu_like
    mu, data, pdf, init_pars, par_bounds, fixed_params, return_fitted_val=True
  File "/home/alguero/.local/lib/python3.7/site-packages/pyhf/infer/mle.py", line 177, in fixed_poi_fit
    return fit(data, pdf, init_pars, par_bounds, fixed_params, **kwargs)
  File "/home/alguero/.local/lib/python3.7/site-packages/pyhf/infer/mle.py", line 110, in fit
    twice_nll, data, pdf, init_pars, par_bounds, fixed_vals, **kwargs
  File "/home/alguero/.local/lib/python3.7/site-packages/pyhf/optimize/mixins.py", line 136, in minimize
    result = self._internal_minimize(**minimizer_kwargs, options=kwargs)
  File "/home/alguero/.local/lib/python3.7/site-packages/pyhf/optimize/mixins.py", line 52, in _internal_minimize
    raise exceptions.FailedMinimization(result)
pyhf.exceptions.FailedMinimization: Optimization failed. Estimated distance to minimum too large.
```
Then I tried using `numpy` as backend and `minuit` as optimizer in our pyhf-SModelS interface but it's about 3x longer and obs and exp CLs are slightly different but still strangely close. `pyhf.set_backend("numpy", "minuit")` is the right usage?

**Comment by kratsg** [comment]
just a quick update, but I will also have @minecreatr looking at this as well (a student).
