### ISSUE TITLE
Precision 32b not working with TPU setup

### ISSUE THREAD

**Issue by rochaporto** [scikit-hep/pyhf#1145]
# Description

I might be doing something wrong, but while trying the hello world example:
```
import jax
import os
import pyhf

from jax.config import config

print("pyhf version: " + pyhf.__version__)
print("jax version: " + jax.__version__)

config.FLAGS.jax_xla_backend = "tpu_driver"
config.FLAGS.jax_backend_target = os.environ['KUBE_GOOGLE_CLOUD_TPU_ENDPOINTS']
print("jax target: " + config.FLAGS.jax_backend_target)
print("jax device count: " + str(jax.device_count()))

pyhf.set_backend('jax', precision="32b")

model = pyhf.simplemodels.hepdata_like(signal_data=[12.0, 11.0], bkg_data=[50.0, 52.0], bkg_uncerts=[3.0, 7.0])
data = [51, 48] + model.config.auxdata
test_mu = 1.0
CLs_obs, CLs_exp = pyhf.infer.hypotest(test_mu, data, model, qtilde=True, return_expected=True)
print(f"Observed: {CLs_obs}, Expected: {CLs_exp}")
```

the GCP TPUs don't look too happy:
```
RuntimeError: Invalid argument: 64-bit data types are not yet supported on the TPU driver API. Convert inputs to float32/int32 before using.
```

# Expected Behavior

Running with 32b should work on TPUs?

# Actual Behavior

Seems the precision is somehow not being taken into account? Here's the traceback:
```
pyhf version: 0.5.2
jax version: 0.2.3
jax target: grpc://10.120.16.90:8470
jax device count: 8
Traceback (most recent call last):
  File "/aaa.py", line 17, in <module>
    model = pyhf.simplemodels.hepdata_like(signal_data=[12.0, 11.0], bkg_data=[50.0, 52.0], bkg_uncerts=[3.0, 7.0])
  File "/usr/local/lib/python3.6/dist-packages/pyhf/simplemodels.py", line 64, in hepdata_like
    return Model(spec, batch_size=batch_size)
  File "/usr/local/lib/python3.6/dist-packages/pyhf/pdf.py", line 575, in __init__
    batch_size=self.batch_size,
  File "/usr/local/lib/python3.6/dist-packages/pyhf/pdf.py", line 435, in __init__
    for k, c in modifiers.combined.items()
  File "/usr/local/lib/python3.6/dist-packages/pyhf/pdf.py", line 435, in <dictcomp>
    for k, c in modifiers.combined.items()
  File "/usr/local/lib/python3.6/dist-packages/pyhf/modifiers/normfactor.py", line 45, in __init__
    self._precompute()
  File "/usr/local/lib/python3.6/dist-packages/pyhf/modifiers/normfactor.py", line 58, in _precompute
    self.normfactor_default = tensorlib.ones(self.normfactor_mask.shape)
  File "/usr/local/lib/python3.6/dist-packages/pyhf/tensor/jax_backend.py", line 190, in ones
    return np.ones(shape)
  File "/usr/local/lib/python3.6/dist-packages/jax/numpy/lax_numpy.py", line 2575, in ones
    return lax.full(shape, 1, dtype)
  File "/usr/local/lib/python3.6/dist-packages/jax/lax/lax.py", line 1396, in full
    return broadcast(fill_value, shape)
  File "/usr/local/lib/python3.6/dist-packages/jax/lax/lax.py", line 650, in broadcast
    return broadcast_in_dim(operand, tuple(sizes) + np.shape(operand), dims)
  File "/usr/local/lib/python3.6/dist-packages/jax/lax/lax.py", line 665, in broadcast_in_dim
    broadcast_dimensions=tuple(broadcast_dimensions))
  File "/usr/local/lib/python3.6/dist-packages/jax/core.py", line 263, in bind
    out = top_trace.process_primitive(self, tracers, params)
  File "/usr/local/lib/python3.6/dist-packages/jax/core.py", line 572, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/usr/local/lib/python3.6/dist-packages/jax/lax/lax.py", line 3053, in _broadcast_in_dim_impl
    operand = _device_put_raw(operand)
  File "/usr/local/lib/python3.6/dist-packages/jax/lax/lax.py", line 1403, in _device_put_raw
    return xla.array_result_handler(None, aval)(*xla.device_put(x))
  File "/usr/local/lib/python3.6/dist-packages/jax/interpreters/xla.py", line 125, in device_put
    return device_put_handlers[type(x)](x, device)
  File "/usr/local/lib/python3.6/dist-packages/jax/interpreters/xla.py", line 133, in _device_put_array
    return (backend.buffer_from_pyval(x, device),)
RuntimeError: Invalid argument: 64-bit data types are not yet supported on the TPU driver API. Convert inputs to float32/int32 before using.
```

# Steps to Reproduce

A TPU running in GCP is required, other than that simply execute the code in the description.

# Checklist

- [ ] Run `git fetch` to get the most up to date version of `master`
- [x] Searched through existing Issues to confirm this is not a duplicate issue
- [x] Filled out the Description, Expected Behavior, Actual Behavior, and Steps to Reproduce sections above or have edited/removed them in a way that fully describes the issue

**Comment by kratsg** [comment]
Problem is here: https://github.com/scikit-hep/pyhf/blob/1e3f729fff94585b5cab64f80d6b516c1bf2b7b6/src/pyhf/tensor/jax_backend.py#L238-L239

(and other lines). We'll need to set a default dtype for ones/zeros (to float? probably) for the current precision.

**Comment by rochaporto** [comment]
Following your pointer, disabling x86 in the jax_backend:
https://github.com/scikit-hep/pyhf/blob/1e3f729fff94585b5cab64f80d6b516c1bf2b7b6/src/pyhf/tensor/jax_backend.py#L3

The code now runs fine on TPUs.
