### ISSUE TITLE
better error message when systematic has wrong number of bins for the channel

### ISSUE THREAD

**Issue by kratsg** [scikit-hep/pyhf#1216]
# Description

It's good that we can catch samples with wrong number of bins for a channel relatively early. We should catch this earlier too for systematics on the samples. Example here has a systematic with 3 bins for a channel with 4 bins:

```json
{
    "channels": [
        {
            "name": "SR",
            "samples": [
                {
                    "data": [
                        1,
                        2,
                        3,
                        4
                    ],
                    "modifiers": [
                        {
                            "data": null,
                            "name": "SigXsecOverSM",
                            "type": "normfactor"
                        }
                    ],
                    "name": "signal"
                },
                {
                    "data": [
                        2,
                        4,
                        6,
                        8
                    ],
                    "modifiers": [
                        {
                            "data": {
                                "hi_data": [
                                    3,
                                    6,
                                    9
                                ],
                                "lo_data": [
                                    1,
                                    2,
                                    3
                                ]
                            },
                            "name": "syst_wrongbins",
                            "type": "histosys"
                        }
                    ],
                    "name": "WtZ"
                }
            ]
        }
    ],
    "measurements": [
        {
            "config": {
                "parameters": [
                    {
                        "bounds": [
                            [
                                -10.0,
                                10.0
                            ]
                        ],
                        "fixed": true,
                        "inits": [
                            1.0
                        ],
                        "name": "SigXsecOverSM"
                    }
                ],
                "poi": "SigXsecOverSM"
            },
            "name": "NormalMeasurement"
        }
    ],
    "observations": [
        {
            "data": [
                2.0,
                2.0,
                2.0,
                2.0
            ],
            "name": "SR"
        }
    ],
    "version": "1.0.0"
}
```

when running `pyhf cls` on this (or just loading in the workspace), the stacktrace is a bit long and crashes in the combined histosys modifier code (a bit further than we'd like)

```
Traceback (most recent call last):
  File "/Users/kratsg/.pyenv/versions/pyhf-dev/bin/pyhf", line 33, in <module>
    sys.exit(load_entry_point('pyhf', 'console_scripts', 'pyhf')())
  File "/Users/kratsg/.pyenv/versions/3.8.6/envs/pyhf-dev/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/kratsg/.pyenv/versions/3.8.6/envs/pyhf-dev/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/kratsg/.pyenv/versions/3.8.6/envs/pyhf-dev/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/kratsg/.pyenv/versions/3.8.6/envs/pyhf-dev/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/kratsg/.pyenv/versions/3.8.6/envs/pyhf-dev/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/kratsg/pyhf/src/pyhf/cli/infer.py", line 198, in cls
    model = ws.model(
  File "/Users/kratsg/pyhf/src/pyhf/workspace.py", line 412, in model
    return Model(modelspec, poi_name=measurement['config']['poi'], **config_kwargs)
  File "/Users/kratsg/pyhf/src/pyhf/pdf.py", line 561, in __init__
    self.main_model = _MainModel(
  File "/Users/kratsg/pyhf/src/pyhf/pdf.py", line 417, in __init__
    self.modifiers_appliers = {
  File "/Users/kratsg/pyhf/src/pyhf/pdf.py", line 418, in <dictcomp>
    k: c(
  File "/Users/kratsg/pyhf/src/pyhf/modifiers/histosys.py", line 63, in __init__
    if histosys_mods:
  File "/Users/kratsg/pyhf/src/pyhf/interpolators/code4p.py", line 22, in __init__
    self._histogramssets = default_backend.astensor(histogramssets)
  File "/Users/kratsg/pyhf/src/pyhf/tensor/numpy_backend.py", line 214, in astensor
    return np.asarray(tensor_in, dtype=dtype)
  File "/Users/kratsg/.pyenv/versions/3.8.6/envs/pyhf-dev/lib/python3.8/site-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: setting an array element with a sequence.
```

The best thing to do is probably say something like "modifier <name> in <sample> has incompatible structure for <channel>" or something similar.

**Comment by matthewfeickert** [comment]
I guess we probably want to check all the modifier data entries length just after model spec creation in 

https://github.com/scikit-hep/pyhf/blob/f25b8ddc6ab34d089954eb4898d54220f7f2defa/src/pyhf/workspace.py#L416-L419

**Comment by matthewfeickert** [comment]
Thinking more on this, I guess this only needs to be applied to bin-wise modifiers, so we shouldn't check after model spec creation, but in each relevant modifier itself.
