### ISSUE TITLE
`RuntimeError` during `shapesys` parameter width calculation

### ISSUE THREAD

**Issue by alexander-held** [scikit-hep/pyhf#1525]
# Description

Filling as a bug report, but this could be argued to not be a bug and working as intended. In that case please view this as a feature request.

# Expected Behavior

I expect `model.config.param_set("...").width()` to succeed for any constrained parameters in `pyhf` models that can be successfully constructed. If the width is ill-defined, a return value of zero or NaN might make sense. This quantity is needed to obtain pre-fit parameter uncertainties for things like pre-fit data/MC plots or pre-fit NP impact calculation. An example implementation is [`cabinetry.model_utils.get_prefit_uncertainties`](https://github.com/alexander-held/cabinetry/blob/37353b56e534eecddb486af8df18598b44a2c27c/src/cabinetry/model_utils.py#L118-L146). The current behavior can be caught in external libraries and handled, but I believe it makes sense to handle this inside `pyhf` already.

# Actual Behavior

`shapesys` parameters with zero width raise a `RuntimeError` when trying to access `.width()`. This can be seen for example in the trilepton workspace (https://doi.org/10.17182/hepdata.99806).

# Steps to Reproduce

Behavior can be reproduced with `pyhf` 0.6.2 and current master (025ffe9). Example setup, built from https://doi.org/10.17182/hepdata.99806 and simplified as much as possible:

```python
import pyhf

spec = {
    "channels": [
        {
            "name": "CRWZ_all_cuts",
            "samples": [
                {
                    "data": [0.17789548635482788],
                    "modifiers": [
                        {"data": None, "name": "mu_SIG", "type": "normfactor"}
                    ],
                    "name": "gaugino_900",
                },
                {
                    "data": [9772.732421875],
                    "modifiers": [
                        {
                            "data": [0.0],
                            "name": "shape_mcstat_Diboson3l_CRWZ_all_obs_cuts",
                            "type": "shapesys",
                        }
                    ],
                    "name": "Diboson3l",
                },
            ],
        }
    ],
    "measurements": [
        {"config": {"parameters": [], "poi": "mu_SIG"}, "name": "NormalMeasurement"}
    ],
    "observations": [{"data": [11544.0], "name": "CRWZ_all_cuts"}],
    "version": "1.0.0",
}

ws = pyhf.Workspace(spec)
model = ws.model()
print(model.config.param_set("shape_mcstat_Diboson3l_CRWZ_all_obs_cuts").width())
```

results in:

```pytb
Traceback (most recent call last):
  File "[...]/pyhf/src/pyhf/parameters/paramsets.py", line 70, in width
    1.0 / default_backend.astensor(self.factors)
AttributeError: 'constrained_by_poisson' object has no attribute 'factors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 38, in <module>
    print(model.config.param_set("shape_mcstat_Diboson3l_CRWZ_all_obs_cuts").width())
  File "[...]/pyhf/src/pyhf/parameters/paramsets.py", line 73, in width
    raise RuntimeError('need to know rate factor to compu')
RuntimeError: need to know rate factor to compu
```

The code runs fine after changing `"data": [0.0]` for the `shape_mcstat_Diboson3l_CRWZ_all_obs_cuts` modifier to a non-zero value.

# Checklist

- [X] Run `git fetch` to get the most up to date version of `master`
- [X] Searched through existing Issues to confirm this is not a duplicate issue
- [X] Filled out the Description, Expected Behavior, Actual Behavior, and Steps to Reproduce sections above or have edited/removed them in a way that fully describes the issue

**Comment by kratsg** [comment]
I'll tag @jdandoy and @lucasflores as well
