### ISSUE TITLE
keras v2.7.0 breaks TensorFlow backend

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#1683]
### Summary

The system of imports that follows once the TensorFlow backend is set causes a 

```pytb
tensorflow.python.framework.errors_impl.AlreadyExistsError: Another metric with the same name already exists.
```

error if [`keras` `v2.7.0`](https://pypi.org/project/keras/2.7.0/) (released today (2021-11-03)) is used, while [`keras` `v2.6.0`](https://pypi.org/project/keras/2.6.0/) is fine.

c.f. [release notes for `keras` `v2.7.0`](https://github.com/tensorflow/tensorflow/releases/tag/v2.7.0-rc1)

### OS / Environment

```console
Linux and macOS in CI
```

### Steps to Reproduce

```python (paste below)
>>> import pyhf
>>> pyhf.set_backend("tensorflow")
```
```pytb
2021-11-03 20:46:06.648339: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/api/keras/optimizers
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/feickert/Code/GitHub/pyhf/src/pyhf/events.py", line 162, in register_wrapper
    result = func(*args, **kwargs)
  File "/home/feickert/Code/GitHub/pyhf/src/pyhf/tensor/manager.py", line 93, in set_backend
    backend = getattr(BackendRetriever, f"{backend:s}_backend")(
  File "/home/feickert/Code/GitHub/pyhf/src/pyhf/tensor/__init__.py", line 41, in __getattr__
    from pyhf.tensor.tensorflow_backend import tensorflow_backend
  File "/home/feickert/Code/GitHub/pyhf/src/pyhf/tensor/tensorflow_backend.py", line 4, in <module>
    import tensorflow_probability as tfp
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/tensorflow_probability/__init__.py", line 20, in <module>
    from tensorflow_probability import substrates
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/tensorflow_probability/substrates/__init__.py", line 21, in <module>
    from tensorflow_probability.python.internal import all_util
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/tensorflow_probability/python/__init__.py", line 142, in <module>
    dir(globals()[pkg_name])  # Forces loading the package from its lazy loader.
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/tensorflow_probability/python/internal/lazy_loader.py", line 61, in __dir__
    module = self._load()
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/tensorflow_probability/python/internal/lazy_loader.py", line 44, in _load
    module = importlib.import_module(self.__name__)
  File "/home/feickert/.pyenv/versions/3.9.6/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/tensorflow_probability/python/experimental/__init__.py", line 35, in <module>
    from tensorflow_probability.python.experimental import bijectors
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/tensorflow_probability/python/experimental/bijectors/__init__.py", line 17, in <module>
    from tensorflow_probability.python.bijectors.ldj_ratio import forward_log_det_jacobian_ratio
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/tensorflow_probability/python/bijectors/__init__.py", line 46, in <module>
    from tensorflow_probability.python.bijectors.glow import Glow
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/tensorflow_probability/python/bijectors/glow.py", line 45, in <module>
    tfkl = tfk.layers
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/tensorflow/python/util/lazy_loader.py", line 62, in __getattr__
    module = self._load()
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/tensorflow/python/util/lazy_loader.py", line 45, in _load
    module = importlib.import_module(self.__name__)
  File "/home/feickert/.pyenv/versions/3.9.6/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/keras/__init__.py", line 25, in <module>
    from keras import models
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/keras/models.py", line 20, in <module>
    from keras import metrics as metrics_module
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/keras/metrics.py", line 26, in <module>
    from keras import activations
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/keras/activations.py", line 20, in <module>
    from keras.layers import advanced_activations
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/keras/layers/__init__.py", line 23, in <module>
    from keras.engine.input_layer import Input
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/keras/engine/input_layer.py", line 21, in <module>
    from keras.engine import base_layer
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/keras/engine/base_layer.py", line 43, in <module>
    from keras.mixed_precision import loss_scale_optimizer
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/keras/mixed_precision/loss_scale_optimizer.py", line 18, in <module>
    from keras import optimizers
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/keras/optimizers.py", line 26, in <module>
    from keras.optimizer_v2 import adadelta as adadelta_v2
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/keras/optimizer_v2/adadelta.py", line 22, in <module>
    from keras.optimizer_v2 import optimizer_v2
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/keras/optimizer_v2/optimizer_v2.py", line 36, in <module>
    keras_optimizers_gauge = tf.__internal__.monitoring.BoolGauge(
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/tensorflow/python/eager/monitoring.py", line 360, in __init__
    super(BoolGauge, self).__init__('BoolGauge', _bool_gauge_methods,
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/tensorflow/python/eager/monitoring.py", line 135, in __init__
    self._metric = self._metric_methods[self._label_length].create(*args)
tensorflow.python.framework.errors_impl.AlreadyExistsError: Another metric with the same name already exists.
```

### Expected Results

No error

### Actual Results

```console
2021-11-03 20:46:06.648339: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/api/keras/optimizers
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/feickert/Code/GitHub/pyhf/src/pyhf/events.py", line 162, in register_wrapper
    result = func(*args, **kwargs)
  File "/home/feickert/Code/GitHub/pyhf/src/pyhf/tensor/manager.py", line 93, in set_backend
    backend = getattr(BackendRetriever, f"{backend:s}_backend")(
  File "/home/feickert/Code/GitHub/pyhf/src/pyhf/tensor/__init__.py", line 41, in __getattr__
    from pyhf.tensor.tensorflow_backend import tensorflow_backend
  File "/home/feickert/Code/GitHub/pyhf/src/pyhf/tensor/tensorflow_backend.py", line 4, in <module>
    import tensorflow_probability as tfp
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/tensorflow_probability/__init__.py", line 20, in <module>
    from tensorflow_probability import substrates
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/tensorflow_probability/substrates/__init__.py", line 21, in <module>
    from tensorflow_probability.python.internal import all_util
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/tensorflow_probability/python/__init__.py", line 142, in <module>
    dir(globals()[pkg_name])  # Forces loading the package from its lazy loader.
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/tensorflow_probability/python/internal/lazy_loader.py", line 61, in __dir__
    module = self._load()
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/tensorflow_probability/python/internal/lazy_loader.py", line 44, in _load
    module = importlib.import_module(self.__name__)
  File "/home/feickert/.pyenv/versions/3.9.6/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/tensorflow_probability/python/experimental/__init__.py", line 35, in <module>
    from tensorflow_probability.python.experimental import bijectors
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/tensorflow_probability/python/experimental/bijectors/__init__.py", line 17, in <module>
    from tensorflow_probability.python.bijectors.ldj_ratio import forward_log_det_jacobian_ratio
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/tensorflow_probability/python/bijectors/__init__.py", line 46, in <module>
    from tensorflow_probability.python.bijectors.glow import Glow
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/tensorflow_probability/python/bijectors/glow.py", line 45, in <module>
    tfkl = tfk.layers
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/tensorflow/python/util/lazy_loader.py", line 62, in __getattr__
    module = self._load()
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/tensorflow/python/util/lazy_loader.py", line 45, in _load
    module = importlib.import_module(self.__name__)
  File "/home/feickert/.pyenv/versions/3.9.6/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/keras/__init__.py", line 25, in <module>
    from keras import models
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/keras/models.py", line 20, in <module>
    from keras import metrics as metrics_module
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/keras/metrics.py", line 26, in <module>
    from keras import activations
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/keras/activations.py", line 20, in <module>
    from keras.layers import advanced_activations
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/keras/layers/__init__.py", line 23, in <module>
    from keras.engine.input_layer import Input
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/keras/engine/input_layer.py", line 21, in <module>
    from keras.engine import base_layer
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/keras/engine/base_layer.py", line 43, in <module>
    from keras.mixed_precision import loss_scale_optimizer
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/keras/mixed_precision/loss_scale_optimizer.py", line 18, in <module>
    from keras import optimizers
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/keras/optimizers.py", line 26, in <module>
    from keras.optimizer_v2 import adadelta as adadelta_v2
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/keras/optimizer_v2/adadelta.py", line 22, in <module>
    from keras.optimizer_v2 import optimizer_v2
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/keras/optimizer_v2/optimizer_v2.py", line 36, in <module>
    keras_optimizers_gauge = tf.__internal__.monitoring.BoolGauge(
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/tensorflow/python/eager/monitoring.py", line 360, in __init__
    super(BoolGauge, self).__init__('BoolGauge', _bool_gauge_methods,
  File "/home/feickert/.pyenv/versions/pyhf-dev-CPU/lib/python3.9/site-packages/tensorflow/python/eager/monitoring.py", line 135, in __init__
    self._metric = self._metric_methods[self._label_length].create(*args)
tensorflow.python.framework.errors_impl.AlreadyExistsError: Another metric with the same name already exists.
```

### pyhf Version

```console
master
```

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by matthewfeickert** [comment]
This is an upstream problem as the same issue can be triggered by the following:

```
$ docker run --rm -ti python:3.9 /bin/bash
root@d3456b886366:/# pip install tensorflow tensorflow_probability
root@d3456b886366:/# pip list | grep 'tensorflow\|keras'
keras                   2.7.0
tensorflow              2.6.1
tensorflow-estimator    2.6.0
tensorflow-probability  0.14.1
root@d3456b886366:/# python -c 'import tensorflow; import tensorflow_probability'
2021-11-04 02:16:08.763413: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-11-04 02:16:08.763453: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-11-04 02:16:09.752346: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/api/keras/optimizers
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/tensorflow_probability/__init__.py", line 20, in <module>
    from tensorflow_probability import substrates
  File "/usr/local/lib/python3.9/site-packages/tensorflow_probability/substrates/__init__.py", line 21, in <module>
    from tensorflow_probability.python.internal import all_util
  File "/usr/local/lib/python3.9/site-packages/tensorflow_probability/python/__init__.py", line 142, in <module>
    dir(globals()[pkg_name])  # Forces loading the package from its lazy loader.
  File "/usr/local/lib/python3.9/site-packages/tensorflow_probability/python/internal/lazy_loader.py", line 61, in __dir__
    module = self._load()
  File "/usr/local/lib/python3.9/site-packages/tensorflow_probability/python/internal/lazy_loader.py", line 44, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.9/site-packages/tensorflow_probability/python/experimental/__init__.py", line 35, in <module>
    from tensorflow_probability.python.experimental import bijectors
  File "/usr/local/lib/python3.9/site-packages/tensorflow_probability/python/experimental/bijectors/__init__.py", line 17, in <module>
    from tensorflow_probability.python.bijectors.ldj_ratio import forward_log_det_jacobian_ratio
  File "/usr/local/lib/python3.9/site-packages/tensorflow_probability/python/bijectors/__init__.py", line 46, in <module>
    from tensorflow_probability.python.bijectors.glow import Glow
  File "/usr/local/lib/python3.9/site-packages/tensorflow_probability/python/bijectors/glow.py", line 45, in <module>
    tfkl = tfk.layers
  File "/usr/local/lib/python3.9/site-packages/tensorflow/python/util/lazy_loader.py", line 62, in __getattr__
    module = self._load()
  File "/usr/local/lib/python3.9/site-packages/tensorflow/python/util/lazy_loader.py", line 45, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.9/site-packages/keras/__init__.py", line 25, in <module>
    from keras import models
  File "/usr/local/lib/python3.9/site-packages/keras/models.py", line 20, in <module>
    from keras import metrics as metrics_module
  File "/usr/local/lib/python3.9/site-packages/keras/metrics.py", line 26, in <module>
    from keras import activations
  File "/usr/local/lib/python3.9/site-packages/keras/activations.py", line 20, in <module>
    from keras.layers import advanced_activations
  File "/usr/local/lib/python3.9/site-packages/keras/layers/__init__.py", line 23, in <module>
    from keras.engine.input_layer import Input
  File "/usr/local/lib/python3.9/site-packages/keras/engine/input_layer.py", line 21, in <module>
    from keras.engine import base_layer
  File "/usr/local/lib/python3.9/site-packages/keras/engine/base_layer.py", line 43, in <module>
    from keras.mixed_precision import loss_scale_optimizer
  File "/usr/local/lib/python3.9/site-packages/keras/mixed_precision/loss_scale_optimizer.py", line 18, in <module>
    from keras import optimizers
  File "/usr/local/lib/python3.9/site-packages/keras/optimizers.py", line 26, in <module>
    from keras.optimizer_v2 import adadelta as adadelta_v2
  File "/usr/local/lib/python3.9/site-packages/keras/optimizer_v2/adadelta.py", line 22, in <module>
    from keras.optimizer_v2 import optimizer_v2
  File "/usr/local/lib/python3.9/site-packages/keras/optimizer_v2/optimizer_v2.py", line 36, in <module>
    keras_optimizers_gauge = tf.__internal__.monitoring.BoolGauge(
  File "/usr/local/lib/python3.9/site-packages/tensorflow/python/eager/monitoring.py", line 360, in __init__
    super(BoolGauge, self).__init__('BoolGauge', _bool_gauge_methods,
  File "/usr/local/lib/python3.9/site-packages/tensorflow/python/eager/monitoring.py", line 135, in __init__
    self._metric = self._metric_methods[self._label_length].create(*args)
tensorflow.python.framework.errors_impl.AlreadyExistsError: Another metric with the same name already exists.
```

and can be seen to be fine with `keras` `v2.6.0` as

```
root@d3456b886366:/# python -m pip install --upgrade "keras<2.7.0"
root@d3456b886366:/# pip list | grep 'tensorflow\|keras'
keras                   2.6.0
tensorflow              2.6.1
tensorflow-estimator    2.6.0
tensorflow-probability  0.14.1
root@d3456b886366:/# python -c 'import tensorflow; import tensorflow_probability'
2021-11-04 02:17:48.941926: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-11-04 02:17:48.941950: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
```

**Comment by matthewfeickert** [comment]
Closing as this is already known in https://github.com/keras-team/keras/issues/15579 and according to https://github.com/keras-team/keras/issues/15579#issuecomment-959826392

>  it will also work once tf 2.7 is released (probably tomorrow).

So let's really hope that the TensorFlow `v2.7.0rc1` flips over to `v2.7.0` tomorrow.

This will also hopefully get fixed in a future TensorFlow `v2.6.X` patch release given https://github.com/tensorflow/tensorflow/pull/52927.

I think everything should be fine once the TensorFlow `2.7.0` release is out given that the only test in the HEAD of dependencies workflow that passed was the pre-release tests which grab all pre-releases with

https://github.com/scikit-hep/pyhf/blob/c493c7c5ad3e5aeda7d022cdf5fe77e9fdab43a2/.github/workflows/dependencies-head.yml#L29

![release-candidates-works](https://user-images.githubusercontent.com/5142394/140247403-2b82a078-1046-4c5f-a155-d0c8c77bbfd0.png)

**Comment by mihaimaruseac** [comment]
Confirming that both TF 2.6.2 and TF 2.7.0 will be released in at most 12-13 hours from now (assuming no build crashed) and this would be fixed. Sorry for the breakage

**Comment by matthewfeickert** [comment]
> Confirming that both TF 2.6.2 and TF 2.7.0 will be released in at most 12-13 hours from now (assuming no build crashed) and this would be fixed.

Awesome. :) That's pretty dang speedy, so thanks!

> Sorry for the breakage

No worries. These things will happen and it is nigh impossible to test everything for these super big projects with so many moving parts.
