### ISSUE TITLE
Documentation of default Minuit strategy choice

### ISSUE THREAD

**Issue by alexander-held** [scikit-hep/pyhf#1785]
### Summary

The documentation of `minuit_optimizer` lists `strategy` as a possible kwarg with default value of `None`, but it does not explain what that choice leads to. `pyhf` uses `0`/`1` depending on whether user-provided gradients are used (#1172 / #1183), and I believe it would be good to have that documented on the optimizer page. I'd be happy to submit a PR.

### Documentation Page Link

https://pyhf.readthedocs.io/en/v0.6.3/_generated/pyhf.optimize.opt_minuit.minuit_optimizer.html#pyhf.optimize.opt_minuit.minuit_optimizer

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by alexander-held** [comment]
Maybe I misunderstood the way `strategy` is supposed to be used, but it seems like `None` is actually not a supported setting:
```
import pyhf

model = pyhf.simplemodels.uncorrelated_background(
    signal=[12.0, 11.0], bkg=[50.0, 52.0], bkg_uncertainty=[3.0, 7.0]
)
data = [51, 48] + model.config.auxdata
pyhf.set_backend("numpy", "minuit")
pyhf.infer.mle.fit(data, model, strategy=None)
```
will fail:
```
Traceback (most recent call last):
  File "[...]/test.py", line 8, in <module>
    pyhf.infer.mle.fit(data, model, strategy=None)
  File "[...]/pyhf/src/pyhf/infer/mle.py", line 131, in fit
    return opt.minimize(
  File "[...]/pyhf/src/pyhf/optimize/mixins.py", line 185, in minimize
    result = self._internal_minimize(
  File "[...]/pyhf/src/pyhf/optimize/mixins.py", line 51, in _internal_minimize
    result = self._minimize(
  File "[...]/pyhf/src/pyhf/optimize/opt_minuit.py", line 117, in _minimize
    minimizer.strategy = strategy
  File "[...]/iminuit/minuit.py", line 203, in strategy
    self._strategy.strategy = value
TypeError: (): incompatible function arguments. The following argument types are supported:
    1. (arg0: iminuit._core.MnStrategy, arg1: int) -> None

Invoked with: <iminuit._core.MnStrategy object at 0x1420a0070>, None
```
`iminuit` only supports values of 0/1/2.

Is the intention from the `pyhf` side to support `None`, or to only support the values of 0/1/2? It is not completely clear to me which of the kwargs on that page is the relevant one (see also #1786).
