### ISSUE TITLE
Hypotest crashing when using toys as it enters the background-like phase 

### ISSUE THREAD

**Issue by backmanification** [scikit-hep/pyhf#1850]
### Summary

When I try to run hypotest on the 501146.json workspace attached in the .zip-file below, I get a crash in the background-like step.

I have made a setup with the environment used in the same zip-file, as well as having added 2 functional workspaces (501145.json and 501172.json) which can be tested using:
```
python min_pyhf.py --dsid 501145
```

### OS / Environment

```console
Software:

    System Software Overview:

      System Version: macOS 12.1 (21C52)
      Kernel Version: Darwin 21.2.0
      Time since boot: 9 days 2:33
```

### Steps to Reproduce

```python (paste below)

```

```console (paste below)
source setup.sh
python min_pyhf.py
```

### File Upload (optional)

[pyhf_crash.zip](https://github.com/scikit-hep/pyhf/files/8531549/pyhf_crash.zip)

### Expected Results

I expected to get CLs values returned, but instead I got a crash.

### Actual Results

```console
(myenv) filip@eduroam-10-200-60-165:~/Downloads/pyhf_crash_repro$ python min_pyhf.py
Starting pyhf job, with the following scipy and pyhf versions
1.8.0
0.6.3
Python path: /usr/local/Cellar/root/6.22.08/lib/root
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Background-like:  40%|█████████████████████████████████████████████████████▌                                                                                | 20/50 [00:00<00:01, 27.28toy/s]/Users/filip/Downloads/pyhf_crash_repro/myenv/lib/python3.9/site-packages/scipy/optimize/_optimize.py:284: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  warnings.warn("Values in x were outside bounds during a "
ERROR:pyhf.optimize.mixins:     fun: 88.82605674511431
     jac: array([-4.46987054e+01,  4.47727269e+01,  4.41489817e-02,  8.69984783e+01,
       -1.58930718e+01,  3.35393037e-01,  2.85607282e+02,  2.17478316e+02,
        2.89304864e+00,  3.25997687e+00,  9.46872126e-03, -9.34536972e-02])
 message: 'Inequality constraints incompatible'
    nfev: 76
     nit: 27
    njev: 24
  status: 4
 success: False
       x: array([ 1.02687839,  1.        , -0.46525842,  0.49134988,  0.78360079,
       -0.71819475, -2.54324715, -2.54324742,  0.49135032,  0.49135032,
        0.09449307,  0.97113262])
Traceback (most recent call last):
  File "/Users/filip/Downloads/pyhf_crash_repro/myenv/lib/python3.9/site-packages/pyhf/optimize/mixins.py", line 61, in _internal_minimize
    assert result.success
AssertionError
Traceback (most recent call last):                                                                                                                                                           
  File "/Users/filip/Downloads/pyhf_crash_repro/myenv/lib/python3.9/site-packages/pyhf/optimize/mixins.py", line 61, in _internal_minimize
    assert result.success
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/filip/Downloads/pyhf_crash_repro/min_pyhf.py", line 55, in <module>
    main()
  File "/Users/filip/Downloads/pyhf_crash_repro/min_pyhf.py", line 43, in main
    output = pyhf.infer.hypotest(args.poival,
  File "/Users/filip/Downloads/pyhf_crash_repro/myenv/lib/python3.9/site-packages/pyhf/infer/__init__.py", line 160, in hypotest
    sig_plus_bkg_distribution, bkg_only_distribution = calc.distributions(poi_test)
  File "/Users/filip/Downloads/pyhf_crash_repro/myenv/lib/python3.9/site-packages/pyhf/infer/calculators.py", line 739, in distributions
    teststat_func(
  File "/Users/filip/Downloads/pyhf_crash_repro/myenv/lib/python3.9/site-packages/pyhf/infer/test_statistics.py", line 189, in qmu_tilde
    return _qmu_like(mu, data, pdf, init_pars, par_bounds, fixed_params)
  File "/Users/filip/Downloads/pyhf_crash_repro/myenv/lib/python3.9/site-packages/pyhf/infer/test_statistics.py", line 25, in _qmu_like
    tmu_like_stat, (_, muhatbhat) = _tmu_like(
  File "/Users/filip/Downloads/pyhf_crash_repro/myenv/lib/python3.9/site-packages/pyhf/infer/test_statistics.py", line 44, in _tmu_like
    mubhathat, fixed_poi_fit_lhood_val = fixed_poi_fit(
  File "/Users/filip/Downloads/pyhf_crash_repro/myenv/lib/python3.9/site-packages/pyhf/infer/mle.py", line 202, in fixed_poi_fit
    return fit(data, pdf, init_pars, par_bounds, fixed_params, **kwargs)
  File "/Users/filip/Downloads/pyhf_crash_repro/myenv/lib/python3.9/site-packages/pyhf/infer/mle.py", line 131, in fit
    return opt.minimize(
  File "/Users/filip/Downloads/pyhf_crash_repro/myenv/lib/python3.9/site-packages/pyhf/optimize/mixins.py", line 184, in minimize
    result = self._internal_minimize(
  File "/Users/filip/Downloads/pyhf_crash_repro/myenv/lib/python3.9/site-packages/pyhf/optimize/mixins.py", line 64, in _internal_minimize
    raise exceptions.FailedMinimization(result)
pyhf.exceptions.FailedMinimization: Inequality constraints incompatible
```

### pyhf Version

```console
pyhf, version 0.6.3
```

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by matthewfeickert** [comment]
@backmanification Thanks for an excellent reproducer. :+1: We'll take a look at this, but realistically it might not be until the weekend or next week as the dev team has some workshops that are going to consume a lot of time in the next few days.

Though taking a quick look at the models, I guess I just want to confirm that you really have a single channel two bin model with observations that are consistent with your background and three orders of magnitude difference between the signal and the background predictions?

(These `jq` queries are terrible and I will clean them up later, but they get the point of my question across for now)

```console
$ jq '.channels[] | {(.name):(.samples[] | select(.name == "bsm_signal") | .data)}' 501146.json 
{
  "channel1": [
    93.2469253540039,
    802.5722045898438
  ]
}
$ jq '.channels[] | {(.name):(.samples[] | select(.name == "bkg") | .data)}' 501146.json 
{
  "channel1": [
    0.49,
    0.69
  ]
}
$ jq '.observations[]' 501146.json 
{
  "data": [
    0.49,
    0.69
  ],
  "name": "channel1"
}

```


If so, I'm not surprised that the model isn't fitting well. Can you elaborate a bit more on the models?

**Comment by backmanification** [comment]
Thank you for a quick reply :) Yes, we're running pyhf over a large set of sample points in a grid with many dimensions, and some of the points can of course be excluded by eye, but to avoid a lot of painstaking fiddling, we were hoping pyhf could handle also these trivial cases and run without crashing. Maybe there are some general guidelines like 'under conditions X, run asymptotics instead of toys since you'll otherwise get crashes'?
We also have other grid points with large yields which do not crash. For example the 501145 workspace, does run through (There are points with even larger yields too that I didn't include in the compressed folder, but I have added one in text below). At this point I don't really get why certain workspaces induce a crash whereas others don't, and it would be great to understand this.
```
{"channels": [{"name": "channel1", "samples": [{"data": [88.50471496582031, 1735.1104736328125], "modifiers": [{"data": null, "name": "lumi", "type": "lumi"}, {"data": null, "name": "mu_si\
g", "type": "normfactor"}, {"data": {"hi": 1.040488908297846, "lo": 0.9595110917021542}, "name": "bsm_uncerts", "type": "normsys"}, {"data": [34.14371280871494, 176.71048585289768], "name"\
: "MCstaterror", "type": "shapesys"}, {"data": {"hi": 1.06728, "lo": 0.93272}, "name": "tracking_uncerts", "type": "normsys"}, {"data": {"hi_data": [97.35518646240236, 1962.3310842619085],\
 "lo_data": [79.65424346923828, 1507.8898630037165]}, "name": "jes_uncerts", "type": "histosys"}, {"data": {"hi_data": [97.35518646240236, 1836.6932057980391], "lo_data": [79.6542434692382\
8, 1633.5277414675859]}, "name": "jer_uncerts", "type": "histosys"}], "name": "bsm_signal"}, {"data": [0.49, 0.69], "modifiers": [{"data": [0.28419999999999995, 0.40019999999999994], "name\
": "staterror_channel1", "type": "shapesys"}, {"data": {"hi_data": [0.4904899999999999, 0.71622], "lo_data": [0.48951, 0.6637799999999999]}, "name": "non_linearity", "type": "histosys"}, {\
"data": {"hi_data": [0.5096, 0.6900689999999999], "lo_data": [0.4704, 0.689931]}, "name": "non_closure", "type": "histosys"}], "name": "bkg"}]}], "measurements": [{"config": {"parameters":\
 [{"auxdata": [1.0], "bounds": [[0.5, 1.5]], "inits": [1.0], "name": "lumi", "sigmas": [0.017]}], "poi": "mu_sig"}, "name": "meas"}], "observations": [{"data": [0.49, 0.69], "name": "chann\
el1"}], "version": "1.0.0"}
```

**Comment by kratsg** [comment]
> we were hoping pyhf could handle also these trivial cases and run without crashing

to be clear, `pyhf` is not meant to make "smart" decisions like this. This is something that is meant to be implemented in a library on top of `pyhf`, rather than `pyhf` itself -- or left up to the user to define their heuristics.
