### ISSUE TITLE
mocker.patch fails to find tensorlib `_setup` attribute for Python 3.11

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#2143]
Now that TensorFlow v2.12.0 is out with Python 3.11 support I've been working to add Python 3.11 to the CI. Everything passes with the exception of the `tests/test_tensor.py` `test_tensorlib_setup` tests

https://github.com/scikit-hep/pyhf/blob/89b3e402f27e98e56eb90cf6ac7ebaa014e4ec25/tests/test_tensor.py#L607-L618

which all fail on 

https://github.com/scikit-hep/pyhf/blob/89b3e402f27e98e56eb90cf6ac7ebaa014e4ec25/tests/test_tensor.py#L615

with errors like

```pytb
___________________ test_tensorlib_setup[64b-numpy_backend] ____________________

tensorlib = 'numpy_backend', precision = '64b'
mocker = <pytest_mock.plugin.MockerFixture object at 0x7fc9557f2e90>

    @pytest.mark.parametrize(
        'tensorlib',
        ['numpy_backend', 'jax_backend', 'pytorch_backend', 'tensorflow_backend'],
    )
    @pytest.mark.parametrize('precision', ['64b', '32b'])
    def test_tensorlib_setup(tensorlib, precision, mocker):
        tb = getattr(pyhf.tensor, tensorlib)(precision=precision)
    
>       func = mocker.patch(f'pyhf.tensor.{tensorlib}._setup')

mocker     = <pytest_mock.plugin.MockerFixture object at 0x7fc9557f2e90>
precision  = '64b'
tb         = <pyhf.tensor.numpy_backend.numpy_backend object at 0x7fca3444fc80>
tensorlib  = 'numpy_backend'

tests/test_tensor.py:605: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/pytest_mock/plugin.py:404: in __call__
    return self._start_patch(
        autospec   = None
        create     = False
        kwargs     = {}
        new        = sentinel.DEFAULT
        new_callable = None
        self       = <pytest_mock.plugin.MockerFixture._Patcher object at 0x7fc9557f00d0>
        spec       = None
        spec_set   = None
        target     = 'pyhf.tensor.numpy_backend._setup'
/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/pytest_mock/plugin.py:214: in _start_patch
    mocked = p.start()  # type: unittest.mock.MagicMock
        args       = ('pyhf.tensor.numpy_backend._setup',)
        kwargs     = {'autospec': None, 'create': False, 'new': sentinel.DEFAULT, 'new_callable': None, ...}
        mock_func  = <function patch at 0x7fcb82251580>
        p          = <unittest.mock._patch object at 0x7fc9557f2[79](https://github.com/scikit-hep/pyhf/actions/runs/4495692762/jobs/7909590551#step:6:80)0>
        self       = <pytest_mock.plugin.MockerFixture._Patcher object at 0x7fc9557f00d0>
        warn_on_mock_enter = True
/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/unittest/mock.py:1585: in start
    result = self.__enter__()
        self       = <unittest.mock._patch object at 0x7fc9557f2790>
/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/unittest/mock.py:1437: in __enter__
    original, local = self.get_original()
        autospec   = None
        kwargs     = {}
        new        = sentinel.DEFAULT
        new_callable = None
        self       = <unittest.mock._patch object at 0x7fc9557f2790>
        spec       = None
        spec_set   = None
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <unittest.mock._patch object at 0x7fc9557f2790>

    def get_original(self):
        target = self.getter()
        name = self.attribute
    
        original = DEFAULT
        local = False
    
        try:
            original = target.__dict__[name]
        except (AttributeError, KeyError):
            original = getattr(target, name, DEFAULT)
        else:
            local = True
    
        if name in _builtins and isinstance(target, ModuleType):
            self.create = True
    
        if not self.create and original is DEFAULT:
>           raise AttributeError(
                "%s does not have the attribute %r" % (target, name)
            )
E           AttributeError: <module 'pyhf.tensor.numpy_backend' from '/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/pyhf/tensor/numpy_backend.py'> does not have the attribute '_setup'

local      = False
name       = '_setup'
original   = sentinel.DEFAULT
self       = <unittest.mock._patch object at 0x7fc9557f27[90](https://github.com/scikit-hep/pyhf/actions/runs/4495692762/jobs/7909590551#step:6:91)>
target     = <module 'pyhf.tensor.numpy_backend' from '/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/pyhf/tensor/numpy_backend.py'>

/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/unittest/mock.py:[141](https://github.com/scikit-hep/pyhf/actions/runs/4495692762/jobs/7909590551#step:6:142)0: AttributeError
```

I'm not sure why as

```python
import pyhf
import pyhf.tensor.numpy_backend
pyhf.tensor.numpy_backend._setup  # <function numpy_backend._setup at 0x7f8466564680>
```

and this is a Python 3.11 error only. :?

**Comment by matthewfeickert** [comment]
From chat @kratsg mentioned the following:

> No, that's a change to inspect in python 3.11
> 
> https://docs.python.org/3/library/unittest.mock.html
>
> > The only exceptions are magic methods and attributes (those that have leading and trailing double underscores). Mock doesn’t create these but instead raises an AttributeError. This is because the interpreter will often implicitly request these methods, and gets very confused to get a new Mock object when it expects a magic method. If you need magic method support see magic methods.
>
> I suspect you need to use name-mangling at that point.

**Comment by matthewfeickert** [comment]
Hm. What is confusing is that this isn't listed in the docs at all for the [`unittest.mock.Mock`](https://docs.python.org/3.11/library/unittest.mock.html#the-mock-class) class and the same information exists for previous releases. So I'm not sure what has changed.

**Comment by matthewfeickert** [comment]
Yeah, it is definitely an issue between `unittest.mock` in Python 3.10 and Python 3.11 that isn't documented as the following script

```python
# mock_debug.py
from unittest.mock import patch

import pyhf

tensor_backend = getattr(pyhf.tensor, "numpy_backend")(precision="64b")

with patch("pyhf.tensor.numpy_backend._setup") as mock_func:
    print(f"{mock_func.call_count=}")
    pyhf.set_backend(tensor_backend)
    print(f"{mock_func.call_count=}")
```

for Python 3.10 works

```console
$ python --version --version && python /tmp/mock_debug.py 
Python 3.10.6 (main, Sep 20 2022, 17:04:13) [GCC 11.2.0]
mock_func.call_count=0
mock_func.call_count=1
```

but for Python 3.11 fails

```console
$ python --version --version && python /tmp/mock_debug.py 
Python 3.11.1 (main, Feb 13 2023, 22:31:08) [GCC 11.3.0]
Traceback (most recent call last):
  File "/tmp/mock_debug.py", line 7, in <module>
    with patch("pyhf.tensor.numpy_backend._setup") as mock_func:
  File "/home/feickert/.pyenv/versions/3.11.1/lib/python3.11/unittest/mock.py", line 1437, in __enter__
    original, local = self.get_original()
                      ^^^^^^^^^^^^^^^^^^^
  File "/home/feickert/.pyenv/versions/3.11.1/lib/python3.11/unittest/mock.py", line 1410, in get_original
    raise AttributeError(
AttributeError: <module 'pyhf.tensor.numpy_backend' from '/home/feickert/Code/GitHub/pyhf/src/pyhf/tensor/numpy_backend.py'> does not have the attribute '_setup'
```

with the same `AttributeError` that we see in the failing test.

**Comment by matthewfeickert** [comment]
Okay the following works across both Python 3.10 and Python 3.11:

```python
# mock_debug.py
from unittest.mock import patch

import pyhf

tensor_backend = getattr(pyhf.tensor, "numpy_backend")(precision="64b")

with patch.object(pyhf.tensor.numpy_backend, "_setup") as mock_func:
    print(f"{mock_func.call_count=}")  # mock_func.call_count=0
    pyhf.set_backend(tensor_backend)
    print(f"{mock_func.call_count=}")  # mock_func.call_count=1
```

**Comment by jiasli** [comment]
Thanks @matthewfeickert, your investigation is really helpful! We are facing a similar issue in our project, so I found this issue.

Finally, I discovered our issue is caused by https://github.com/python/cpython/pull/18544 which changes the logic of `unittest.mock._get_target` to use `pkgutil.resolve_name`. This changes how the `'pyhf.tensor.numpy_backend'` string is resolved:

```py
import pkgutil

# _dot_lookup and _importer are copied from Python 3.10
def _dot_lookup(thing, comp, import_path):
    try:
        return getattr(thing, comp)
    except AttributeError:
        __import__(import_path)
        return getattr(thing, comp)


def _importer(target):
    components = target.split('.')
    import_path = components.pop(0)
    thing = __import__(import_path)

    for comp in components:
        import_path += ".%s" % comp
        thing = _dot_lookup(thing, comp, import_path)
    return thing


print(pkgutil.resolve_name('pyhf.tensor.numpy_backend'))
print(_importer('pyhf.tensor.numpy_backend'))
```

Output:

```
<module 'pyhf.tensor.numpy_backend' from 'D:\\cli\\py311\\Lib\\site-packages\\pyhf\\tensor\\numpy_backend.py'>
<class 'pyhf.tensor.numpy_backend.numpy_backend'>
```

Because `pkgutil.resolve_name` resolves `'pyhf.tensor.numpy_backend'` to `pyhf/tensor/numpy_backend.py` module and that module doesn't have `_setup`, `unittest.mock.patch` raises that `AttributeError`. It seems `pkgutil.resolve_name` doesn't take the "re-binding" code into consideration:

https://github.com/scikit-hep/pyhf/blob/bd8c21a33b2f3ce8b41ea78cb351eef91c21b92b/src/pyhf/__init__.py#L1

https://github.com/scikit-hep/pyhf/blob/bd8c21a33b2f3ce8b41ea78cb351eef91c21b92b/src/pyhf/tensor/__init__.py#L24

**Comment by matthewfeickert** [comment]
Thanks very much for this great summary @jiasli! :raised_hands: I'll have to revisit this myself in the near future.
