### ISSUE TITLE
pyhf v0.7.3 docs fail on ReadTheDocs for Sphinx v7.2.1

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#2297]
The ReadTheDocs build for `pyhf` `v0.7.3` is failing as in the time between PR #2294 and now [Sphinx `v7.2.0`](https://pypi.org/project/Sphinx/7.2.0/) and [Sphinx `v7.2.1`](https://pypi.org/project/Sphinx/7.2.0/) came out and broke things

ReadTheDocs broken build: https://readthedocs.org/projects/pyhf/builds/21640438/

```
python -m sphinx -T -E -b readthedocssinglehtmllocalmedia -d _build/doctrees -D language=en . $READTHEDOCS_OUTPUT/htmlzip
```
```pytb
Running Sphinx v7.2.1
WARNING: The config value `jupyterlite_dir' has type `str', defaults to `PosixPath'.
checking bibtex cache... out of date
parsing bibtex file /home/docs/checkouts/readthedocs.org/user_builds/pyhf/checkouts/v0.7.3/docs/bib/docs.bib... parsed 10 entries
parsing bibtex file /home/docs/checkouts/readthedocs.org/user_builds/pyhf/checkouts/v0.7.3/docs/bib/HEPData_likelihoods.bib... parsed 25 entries
parsing bibtex file /home/docs/checkouts/readthedocs.org/user_builds/pyhf/checkouts/v0.7.3/docs/bib/media.bib... parsed 4 entries
parsing bibtex file /home/docs/checkouts/readthedocs.org/user_builds/pyhf/checkouts/v0.7.3/docs/bib/posters.bib... parsed 3 entries
parsing bibtex file /home/docs/checkouts/readthedocs.org/user_builds/pyhf/checkouts/v0.7.3/docs/bib/preferred.bib... parsed 2 entries
parsing bibtex file /home/docs/checkouts/readthedocs.org/user_builds/pyhf/checkouts/v0.7.3/docs/bib/talks.bib... parsed 25 entries
parsing bibtex file /home/docs/checkouts/readthedocs.org/user_builds/pyhf/checkouts/v0.7.3/docs/bib/tutorials.bib... parsed 5 entries
parsing bibtex file /home/docs/checkouts/readthedocs.org/user_builds/pyhf/checkouts/v0.7.3/docs/bib/use_citations.bib... parsed 55 entries
parsing bibtex file /home/docs/checkouts/readthedocs.org/user_builds/pyhf/checkouts/v0.7.3/docs/bib/general_citations.bib... parsed 16 entries
[autosummary] generating autosummary for: _generated/pyhf.compat.interpret_rootname.rst, _generated/pyhf.compat.paramset_to_rootnames.rst, _generated/pyhf.compat.rst, _generated/pyhf.contrib.utils.download.rst, _generated/pyhf.contrib.viz.brazil.BrazilBandCollection.rst, _generated/pyhf.contrib.viz.brazil.plot_brazil_band.rst, _generated/pyhf.contrib.viz.brazil.plot_cls_components.rst, _generated/pyhf.contrib.viz.brazil.plot_results.rst, _generated/pyhf.contrib.viz.brazil.rst, _generated/pyhf.exceptions.ImportBackendError.rst, ..., release-notes/v0.5.3.rst, release-notes/v0.5.4.rst, release-notes/v0.6.0.rst, release-notes/v0.6.1.rst, release-notes/v0.6.2.rst, release-notes/v0.6.3.rst, release-notes/v0.7.0.rst, release-notes/v0.7.1.rst, release-notes/v0.7.2.rst, release-notes/v0.7.3.rst
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://numpy.org/doc/stable/objects.inv...
loading intersphinx inventory from https://docs.scipy.org/doc/scipy/objects.inv...
loading intersphinx inventory from https://matplotlib.org/stable/objects.inv...
loading intersphinx inventory from https://iminuit.readthedocs.io/en/stable/objects.inv...
loading intersphinx inventory from https://uproot.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://python-json-patch.readthedocs.io/en/latest/objects.inv...
building [mo]: targets for 0 po files that are out of date
writing output... 
building [readthedocssinglehtmllocalmedia]: all documents
updating environment: [new config] 161 added, 0 changed, 0 removed
[2Kreading sources... [  1%] _generated/pyhf.compat
[2Kreading sources... [  1%] _generated/pyhf.compat.interpret_rootname
[2Kreading sources... [  2%] _generated/pyhf.compat.paramset_to_rootnames
[2Kreading sources... [  2%] _generated/pyhf.contrib.utils.download
[2Kreading sources... [  3%] _generated/pyhf.contrib.viz.brazil
[2Kreading sources... [  4%] _generated/pyhf.contrib.viz.brazil.BrazilBandCollection
[2Kreading sources... [  4%] _generated/pyhf.contrib.viz.brazil.plot_brazil_band
[2Kreading sources... [  5%] _generated/pyhf.contrib.viz.brazil.plot_cls_components
[2Kreading sources... [  6%] _generated/pyhf.contrib.viz.brazil.plot_results
[2Kreading sources... [  6%] _generated/pyhf.exceptions.ImportBackendError
[2Kreading sources... [  7%] _generated/pyhf.exceptions.InvalidBackend
[2Kreading sources... [  7%] _generated/pyhf.exceptions.InvalidInterpCode
[2Kreading sources... [  8%] _generated/pyhf.exceptions.InvalidMeasurement
[2Kreading sources... [  9%] _generated/pyhf.exceptions.InvalidModel
[2Kreading sources... [  9%] _generated/pyhf.exceptions.InvalidModifier
[2Kreading sources... [ 10%] _generated/pyhf.exceptions.InvalidNameReuse
[2Kreading sources... [ 11%] _generated/pyhf.exceptions.InvalidOptimizer
[2Kreading sources... [ 11%] _generated/pyhf.exceptions.InvalidPatchLookup
[2Kreading sources... [ 12%] _generated/pyhf.exceptions.InvalidPatchSet
[2Kreading sources... [ 12%] _generated/pyhf.exceptions.InvalidPdfData
[2Kreading sources... [ 13%] _generated/pyhf.exceptions.InvalidPdfParameters
[2Kreading sources... [ 14%] _generated/pyhf.exceptions.InvalidSpecification
[2Kreading sources... [ 14%] _generated/pyhf.exceptions.InvalidWorkspaceOperation
[2Kreading sources... [ 15%] _generated/pyhf.exceptions.PatchSetVerificationError
[2Kreading sources... [ 16%] _generated/pyhf.get_backend
[2Kreading sources... [ 16%] _generated/pyhf.infer.calculators.AsymptoticCalculator
[2Kreading sources... [ 17%] _generated/pyhf.infer.calculators.AsymptoticTestStatDistribution
[2Kreading sources... [ 17%] _generated/pyhf.infer.calculators.EmpiricalDistribution
[2Kreading sources... [ 18%] _generated/pyhf.infer.calculators.HypoTestFitResults
[2Kreading sources... [ 19%] _generated/pyhf.infer.calculators.ToyCalculator
[2Kreading sources... [ 19%] _generated/pyhf.infer.calculators.generate_asimov_data
[2Kreading sources... [ 20%] _generated/pyhf.infer.hypotest
[2Kreading sources... [ 20%] _generated/pyhf.infer.intervals.upper_limits.linear_grid_scan
[2Kreading sources... [ 21%] _generated/pyhf.infer.intervals.upper_limits.toms748_scan
[2Kreading sources... [ 22%] _generated/pyhf.infer.intervals.upper_limits.upper_limit
[2Kreading sources... [ 22%] _generated/pyhf.infer.intervals.upperlimit
[2Kreading sources... [ 23%] _generated/pyhf.infer.mle.fit
[2Kreading sources... [ 24%] _generated/pyhf.infer.mle.fixed_poi_fit
[2Kreading sources... [ 24%] _generated/pyhf.infer.mle.twice_nll
[2Kreading sources... [ 25%] _generated/pyhf.infer.test_statistics.q0
[2Kreading sources... [ 25%] _generated/pyhf.infer.test_statistics.qmu
[2Kreading sources... [ 26%] _generated/pyhf.infer.test_statistics.qmu_tilde
[2Kreading sources... [ 27%] _generated/pyhf.infer.test_statistics.tmu
[2Kreading sources... [ 27%] _generated/pyhf.infer.test_statistics.tmu_tilde
[2Kreading sources... [ 28%] _generated/pyhf.infer.utils.all_pois_floating
[2Kreading sources... [ 29%] _generated/pyhf.infer.utils.create_calculator
[2Kreading sources... [ 29%] _generated/pyhf.infer.utils.get_test_stat
[2Kreading sources... [ 30%] _generated/pyhf.interpolators.code0
[2Kreading sources... [ 30%] _generated/pyhf.interpolators.code1
[2Kreading sources... [ 31%] _generated/pyhf.interpolators.code2
[2Kreading sources... [ 32%] _generated/pyhf.interpolators.code4
[2Kreading sources... [ 32%] _generated/pyhf.interpolators.code4p
[2Kreading sources... [ 33%] _generated/pyhf.mixins._ChannelSummaryMixin
[2Kreading sources... [ 34%] _generated/pyhf.modifiers.histosys
[2Kreading sources... [ 34%] _generated/pyhf.modifiers.histosys.histosys_builder
[2Kreading sources... [ 35%] _generated/pyhf.modifiers.histosys.histosys_combined
[2Kreading sources... [ 35%] _generated/pyhf.modifiers.histosys.required_parset
[2Kreading sources... [ 36%] _generated/pyhf.modifiers.normfactor
[2Kreading sources... [ 37%] _generated/pyhf.modifiers.normfactor.normfactor_builder
[2Kreading sources... [ 37%] _generated/pyhf.modifiers.normfactor.normfactor_combined
[2Kreading sources... [ 38%] _generated/pyhf.modifiers.normfactor.required_parset
[2Kreading sources... [ 39%] _generated/pyhf.modifiers.normsys
[2Kreading sources... [ 39%] _generated/pyhf.modifiers.normsys.normsys_builder
[2Kreading sources... [ 40%] _generated/pyhf.modifiers.normsys.normsys_combined
[2Kreading sources... [ 40%] _generated/pyhf.modifiers.normsys.required_parset
[2Kreading sources... [ 41%] _generated/pyhf.modifiers.shapefactor
[2Kreading sources... [ 42%] _generated/pyhf.modifiers.shapefactor.required_parset
[2Kreading sources... [ 42%] _generated/pyhf.modifiers.shapefactor.shapefactor_builder
[2Kreading sources... [ 43%] _generated/pyhf.modifiers.shapefactor.shapefactor_combined
[2Kreading sources... [ 43%] _generated/pyhf.modifiers.shapesys
[2Kreading sources... [ 44%] _generated/pyhf.modifiers.shapesys.required_parset
[2Kreading sources... [ 45%] _generated/pyhf.modifiers.shapesys.shapesys_builder
[2Kreading sources... [ 45%] _generated/pyhf.modifiers.shapesys.shapesys_combined
[2Kreading sources... [ 46%] _generated/pyhf.modifiers.staterror
[2Kreading sources... [ 47%] _generated/pyhf.modifiers.staterror.required_parset
[2Kreading sources... [ 47%] _generated/pyhf.modifiers.staterror.staterror_builder
[2Kreading sources... [ 48%] _generated/pyhf.modifiers.staterror.staterror_combined
[2Kreading sources... [ 48%] _generated/pyhf.optimize.mixins.OptimizerMixin
[2Kreading sources... [ 49%] _generated/pyhf.optimize.opt_minuit.minuit_optimizer
[2Kreading sources... [ 50%] _generated/pyhf.optimize.opt_scipy.scipy_optimizer
[2Kreading sources... [ 50%] _generated/pyhf.optimizer
[2Kreading sources... [ 51%] _generated/pyhf.patchset.Patch
[2Kreading sources... [ 52%] _generated/pyhf.patchset.PatchSet
[2Kreading sources... [ 52%] _generated/pyhf.pdf.Model
[2Kreading sources... [ 53%] _generated/pyhf.pdf._ModelConfig
[2Kreading sources... [ 53%] _generated/pyhf.probability.Independent
[2Kreading sources... [ 54%] _generated/pyhf.probability.Normal
[2Kreading sources... [ 55%] _generated/pyhf.probability.Poisson
[2Kreading sources... [ 55%] _generated/pyhf.probability.Simultaneous
[2Kreading sources... [ 56%] _generated/pyhf.readxml
[2Kreading sources... [ 57%] _generated/pyhf.readxml.clear_filecache
[2Kreading sources... [ 57%] _generated/pyhf.readxml.dedupe_parameters
[2Kreading sources... [ 58%] _generated/pyhf.readxml.extract_error
[2Kreading sources... [ 58%] _generated/pyhf.readxml.import_root_histogram
[2Kreading sources... [ 59%] _generated/pyhf.readxml.parse
[2Kreading sources... [ 60%] _generated/pyhf.readxml.process_channel
[2Kreading sources... [ 60%] _generated/pyhf.readxml.process_data
[2Kreading sources... [ 61%] _generated/pyhf.readxml.process_measurements
[2Kreading sources... [ 61%] _generated/pyhf.readxml.process_sample
[2Kreading sources... [ 62%] _generated/pyhf.schema
[2Kreading sources... [ 63%] _generated/pyhf.schema.Schema
[2Kreading sources... [ 63%] _generated/pyhf.schema.load_schema
[2Kreading sources... [ 64%] _generated/pyhf.schema.validate
[2Kreading sources... [ 65%] _generated/pyhf.set_backend
[2Kreading sources... [ 65%] _generated/pyhf.simplemodels.correlated_background
[2Kreading sources... [ 66%] _generated/pyhf.simplemodels.uncorrelated_background
[2Kreading sources... [ 66%] _generated/pyhf.tensor.jax_backend.jax_backend
[2Kreading sources... [ 67%] _generated/pyhf.tensor.numpy_backend.numpy_backend
[2Kreading sources... [ 68%] _generated/pyhf.tensor.pytorch_backend.pytorch_backend
[2Kreading sources... [ 68%] _generated/pyhf.tensor.tensorflow_backend.tensorflow_backend
[2Kreading sources... [ 69%] _generated/pyhf.tensorlib
[2Kreading sources... [ 70%] _generated/pyhf.utils.citation
[2Kreading sources... [ 70%] _generated/pyhf.utils.digest
[2Kreading sources... [ 71%] _generated/pyhf.utils.options_from_eqdelimstring
[2Kreading sources... [ 71%] _generated/pyhf.workspace.Workspace
[2Kreading sources... [ 72%] _generated/pyhf.writexml
[2Kreading sources... [ 73%] _generated/pyhf.writexml.build_channel
[2Kreading sources... [ 73%] _generated/pyhf.writexml.build_data
[2Kreading sources... [ 74%] _generated/pyhf.writexml.build_measurement
[2Kreading sources... [ 75%] _generated/pyhf.writexml.build_modifier
[2Kreading sources... [ 75%] _generated/pyhf.writexml.build_sample
[2Kreading sources... [ 76%] _generated/pyhf.writexml.indent
[2Kreading sources... [ 76%] api
[2Kreading sources... [ 77%] babel
[2Kreading sources... [ 78%] citations
[2Kreading sources... [ 78%] cli
[2Kreading sources... [ 79%] contributors
[2Kreading sources... [ 80%] development
[2Kreading sources... [ 80%] examples
[2Kreading sources... [ 81%] examples/notebooks/ShapeFactor
/home/docs/checkouts/readthedocs.org/user_builds/pyhf/envs/v0.7.3/lib/python3.11/site-packages/nbsphinx/__init__.py:1058: RuntimeWarning: You are using an unsupported version of pandoc (2.9.2.1).
Your version must be at least (2.14.2) but less than (4.0.0).
Refer to https://pandoc.org/installing.html.
Continuing with doubts...
  nbconvert.utils.pandoc.check_pandoc_version()
[2Kreading sources... [ 81%] examples/notebooks/XML_ImportExport
[2Kreading sources... [ 82%] examples/notebooks/altair
[2Kreading sources... [ 83%] examples/notebooks/binderexample/StatisticalAnalysis
[2Kreading sources... [ 83%] examples/notebooks/hello-world
[2Kreading sources... [ 84%] examples/notebooks/learn/InterpolationCodes
[2Kreading sources... [ 84%] examples/notebooks/learn/TensorizingInterpolations
[2Kreading sources... [ 85%] examples/notebooks/learn/TestStatistics
[2Kreading sources... [ 86%] examples/notebooks/learn/UsingCalculators
[2Kreading sources... [ 86%] examples/notebooks/multiBinPois
[2Kreading sources... [ 87%] examples/notebooks/multichannel-coupled-histo
[2Kreading sources... [ 88%] examples/notebooks/toys
[2Kreading sources... [ 88%] faq
[2Kreading sources... [ 89%] governance/ROADMAP
[2Kreading sources... [ 89%] index
[2Kreading sources... [ 90%] installation
[2Kreading sources... [ 91%] intro
[2Kreading sources... [ 91%] jupyterlite
[2Kreading sources... [ 92%] learn
[2Kreading sources... [ 93%] likelihood
[2Kreading sources... [ 93%] outreach
[2Kreading sources... [ 94%] release-notes
[2Kreading sources... [ 94%] release-notes/v0.5.3
[2Kreading sources... [ 95%] release-notes/v0.5.4
[2Kreading sources... [ 96%] release-notes/v0.6.0
[2Kreading sources... [ 96%] release-notes/v0.6.1
[2Kreading sources... [ 97%] release-notes/v0.6.2
[2Kreading sources... [ 98%] release-notes/v0.6.3
[2Kreading sources... [ 98%] release-notes/v0.7.0
[2Kreading sources... [ 99%] release-notes/v0.7.1
[2Kreading sources... [ 99%] release-notes/v0.7.2
[2Kreading sources... [100%] release-notes/v0.7.3
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
assembling single document... intro likelihood learn examples/notebooks/learn/InterpolationCodes examples/notebooks/learn/TensorizingInterpolations examples/notebooks/learn/TestStatistics examples/notebooks/learn/UsingCalculators examples examples/notebooks/ShapeFactor examples/notebooks/XML_ImportExport examples/notebooks/altair examples/notebooks/hello-world examples/notebooks/multiBinPois examples/notebooks/multichannel-coupled-histo examples/notebooks/toys examples/notebooks/binderexample/StatisticalAnalysis outreach installation development faq babel cli api _generated/pyhf.tensorlib _generated/pyhf.optimizer _generated/pyhf.get_backend _generated/pyhf.set_backend _generated/pyhf.readxml _generated/pyhf.readxml.clear_filecache _generated/pyhf.readxml.dedupe_parameters _generated/pyhf.readxml.extract_error _generated/pyhf.readxml.import_root_histogram _generated/pyhf.readxml.parse _generated/pyhf.readxml.process_channel _generated/pyhf.readxml.process_data _generated/pyhf.readxml.process_measurements _generated/pyhf.readxml.process_sample _generated/pyhf.writexml _generated/pyhf.writexml.build_channel _generated/pyhf.writexml.build_data _generated/pyhf.writexml.build_measurement _generated/pyhf.writexml.build_modifier _generated/pyhf.writexml.build_sample _generated/pyhf.writexml.indent _generated/pyhf.compat _generated/pyhf.compat.interpret_rootname _generated/pyhf.compat.paramset_to_rootnames _generated/pyhf.schema _generated/pyhf.probability.Normal _generated/pyhf.probability.Poisson _generated/pyhf.probability.Independent _generated/pyhf.probability.Simultaneous _generated/pyhf.pdf.Model _generated/pyhf.pdf._ModelConfig _generated/pyhf.mixins._ChannelSummaryMixin _generated/pyhf.workspace.Workspace _generated/pyhf.patchset.PatchSet _generated/pyhf.patchset.Patch _generated/pyhf.simplemodels.uncorrelated_background _generated/pyhf.simplemodels.correlated_background _generated/pyhf.tensor.numpy_backend.numpy_backend _generated/pyhf.tensor.pytorch_backend.pytorch_backend _generated/pyhf.tensor.tensorflow_backend.tensorflow_backend _generated/pyhf.tensor.jax_backend.jax_backend _generated/pyhf.optimize.mixins.OptimizerMixin _generated/pyhf.optimize.opt_scipy.scipy_optimizer _generated/pyhf.optimize.opt_minuit.minuit_optimizer _generated/pyhf.modifiers.histosys _generated/pyhf.modifiers.histosys.histosys_builder _generated/pyhf.modifiers.histosys.histosys_combined _generated/pyhf.modifiers.histosys.required_parset _generated/pyhf.modifiers.normfactor _generated/pyhf.modifiers.normfactor.normfactor_builder _generated/pyhf.modifiers.normfactor.normfactor_combined _generated/pyhf.modifiers.normfactor.required_parset _generated/pyhf.modifiers.normsys _generated/pyhf.modifiers.normsys.normsys_builder _generated/pyhf.modifiers.normsys.normsys_combined _generated/pyhf.modifiers.normsys.required_parset _generated/pyhf.modifiers.shapefactor _generated/pyhf.modifiers.shapefactor.shapefactor_builder _generated/pyhf.modifiers.shapefactor.shapefactor_combined _generated/pyhf.modifiers.shapefactor.required_parset _generated/pyhf.modifiers.shapesys _generated/pyhf.modifiers.shapesys.shapesys_builder _generated/pyhf.modifiers.shapesys.shapesys_combined _generated/pyhf.modifiers.shapesys.required_parset _generated/pyhf.modifiers.staterror _generated/pyhf.modifiers.staterror.staterror_builder _generated/pyhf.modifiers.staterror.staterror_combined _generated/pyhf.modifiers.staterror.required_parset _generated/pyhf.interpolators.code0 _generated/pyhf.interpolators.code1 _generated/pyhf.interpolators.code2 _generated/pyhf.interpolators.code4 _generated/pyhf.interpolators.code4p _generated/pyhf.infer.test_statistics.q0 _generated/pyhf.infer.test_statistics.qmu _generated/pyhf.infer.test_statistics.qmu_tilde _generated/pyhf.infer.test_statistics.tmu _generated/pyhf.infer.test_statistics.tmu_tilde _generated/pyhf.infer.utils.get_test_stat _generated/pyhf.infer.calculators.generate_asimov_data _generated/pyhf.infer.calculators.HypoTestFitResults _generated/pyhf.infer.calculators.AsymptoticTestStatDistribution _generated/pyhf.infer.calculators.EmpiricalDistribution _generated/pyhf.infer.calculators.AsymptoticCalculator _generated/pyhf.infer.calculators.ToyCalculator _generated/pyhf.infer.utils.create_calculator _generated/pyhf.infer.mle.twice_nll _generated/pyhf.infer.mle.fit _generated/pyhf.infer.mle.fixed_poi_fit _generated/pyhf.infer.hypotest _generated/pyhf.infer.utils.all_pois_floating _generated/pyhf.infer.intervals.upper_limits.upper_limit _generated/pyhf.infer.intervals.upper_limits.toms748_scan _generated/pyhf.infer.intervals.upper_limits.linear_grid_scan _generated/pyhf.infer.intervals.upperlimit _generated/pyhf.schema.Schema _generated/pyhf.schema.load_schema _generated/pyhf.schema.validate _generated/pyhf.exceptions.InvalidMeasurement _generated/pyhf.exceptions.InvalidNameReuse _generated/pyhf.exceptions.InvalidSpecification _generated/pyhf.exceptions.InvalidPatchSet _generated/pyhf.exceptions.InvalidPatchLookup _generated/pyhf.exceptions.PatchSetVerificationError _generated/pyhf.exceptions.InvalidWorkspaceOperation _generated/pyhf.exceptions.InvalidModel _generated/pyhf.exceptions.InvalidModifier _generated/pyhf.exceptions.InvalidInterpCode _generated/pyhf.exceptions.ImportBackendError _generated/pyhf.exceptions.InvalidBackend _generated/pyhf.exceptions.InvalidOptimizer _generated/pyhf.exceptions.InvalidPdfParameters _generated/pyhf.exceptions.InvalidPdfData _generated/pyhf.utils.options_from_eqdelimstring _generated/pyhf.utils.digest _generated/pyhf.utils.citation _generated/pyhf.contrib.viz.brazil _generated/pyhf.contrib.viz.brazil.BrazilBandCollection _generated/pyhf.contrib.viz.brazil.plot_brazil_band _generated/pyhf.contrib.viz.brazil.plot_cls_components _generated/pyhf.contrib.viz.brazil.plot_results _generated/pyhf.contrib.utils.download citations governance/ROADMAP release-notes contributors done
writing... failed

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyhf/envs/v0.7.3/lib/python3.11/site-packages/sphinx/builders/html/__init__.py", line 1121, in handle_page
    output = self.templates.render(templatename, ctx)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyhf/envs/v0.7.3/lib/python3.11/site-packages/sphinx/jinja2glue.py", line 201, in render
    return self.environment.get_template(template).render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyhf/envs/v0.7.3/lib/python3.11/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyhf/envs/v0.7.3/lib/python3.11/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyhf/envs/v0.7.3/lib/python3.11/site-packages/sphinx/themes/basic/page.html", line 10, in top-level template code
    {%- extends "layout.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyhf/envs/v0.7.3/lib/python3.11/site-packages/sphinx_rtd_theme/layout.html", line 164, in top-level template code
    {%- block navigation %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyhf/envs/v0.7.3/lib/python3.11/site-packages/sphinx_rtd_theme/layout.html", line 167, in block 'navigation'
    {%- block menu %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyhf/envs/v0.7.3/lib/python3.11/site-packages/sphinx_rtd_theme/layout.html", line 168, in block 'menu'
    {%- set toctree = toctree(maxdepth=theme_navigation_depth|int,
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyhf/envs/v0.7.3/lib/python3.11/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyhf/envs/v0.7.3/lib/python3.11/site-packages/sphinx/builders/html/__init__.py", line 1048, in <lambda>
    ctx['toctree'] = lambda **kwargs: self._get_local_toctree(pagename, **kwargs)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyhf/envs/v0.7.3/lib/python3.11/site-packages/sphinx/builders/singlehtml.py", line 67, in _get_local_toctree
    if kwargs.get('includehidden', 'false').lower() == 'false':
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'bool' object has no attribute 'lower'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyhf/envs/v0.7.3/lib/python3.11/site-packages/sphinx/cmd/build.py", line 298, in build_main
    app.build(args.force_all, args.filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyhf/envs/v0.7.3/lib/python3.11/site-packages/sphinx/application.py", line 355, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyhf/envs/v0.7.3/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 290, in build_update
    self.build(['__all__'], to_build)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyhf/envs/v0.7.3/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 363, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyhf/envs/v0.7.3/lib/python3.11/site-packages/sphinx/builders/singlehtml.py", line 165, in write
    self.write_doc(self.config.root_doc, doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyhf/envs/v0.7.3/lib/python3.11/site-packages/sphinx/builders/html/__init__.py", line 655, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyhf/envs/v0.7.3/lib/python3.11/site-packages/sphinx/builders/html/__init__.py", line 1128, in handle_page
    raise ThemeError(__("An error happened in rendering the page %s.\nReason: %r") %
sphinx.errors.ThemeError: An error happened in rendering the page index.
Reason: AttributeError("'bool' object has no attribute 'lower'")

Theme error:
An error happened in rendering the page index.
Reason: AttributeError("'bool' object has no attribute 'lower'")
```

**Comment by matthewfeickert** [comment]
I've temporarily fixed the docs from totally breaking by fixing the default url to https://pyhf.readthedocs.io/en/v0.7.2/

**Comment by AA-Turner** [comment]
https://github.com/sphinx-doc/sphinx/issues/11607

**Comment by matthewfeickert** [comment]
Thanks very much @AA-Turner.

**Comment by AA-Turner** [comment]
[Sphinx 7.2.2](https://pypi.org/project/Sphinx/7.2.2/) has been released.

A

**Comment by matthewfeickert** [comment]
This is resolved now. Thank you @AA-Turner and Sphinx team!
