### ISSUE TITLE
Investigate use of jax

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#416]
# Description

As a compliment/replacement to Issue #79, consider using [JAX: Autograd and XLA](https://github.com/google/jax). This should be investigated and some examples made up.

**Comment by matthewfeickert** [comment]
Now that Jax has Poissons as of PR https://github.com/google/jax/pull/1608 I think everything that is needed for PR #377 to move forward again.

**Comment by matthewfeickert** [comment]
Spoke too soon. The version that was implemented in https://github.com/google/jax/pull/1608 doesn't have the distributions implemented:

```python
>>> import pyhf
>>> pyhf.set_backend(pyhf.tensor.numpy_backend())
>>> rates = pyhf.tensorlib.astensor([5, 8])
>>> values = pyhf.tensorlib.astensor([4, 9])
>>> poissons = pyhf.tensorlib.poisson_dist(rates)
>>> poissons.sample((5,))
array([[ 3,  7],
       [ 8,  6],
       [ 6, 13],
       [11,  5],
       [ 4,  7]])
>>>
>>> pyhf.set_backend(pyhf.tensor.jax_backend())
>>> rates = pyhf.tensorlib.astensor([5, 8])
>>> values = pyhf.tensorlib.astensor([4, 9])
>>> poissons = pyhf.tensorlib.poisson_dist(rates)
>>> poissons.sample((5,))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/feickert/Code/GitHub/pyhf/src/pyhf/tensor/jax_backend.py", line 16, in sample
    return poisson(self.rate).rvs(size=sample_shape + self.rate.shape)
TypeError: 'module' object is not callable
```

Though it seems that this is also the case with how the Normal distribution is implemented, so I'll have to look into it.

```
>>> import pyhf
>>> pyhf.set_backend(pyhf.tensor.jax_backend())
>>> means = pyhf.tensorlib.astensor([5, 8])
>>> stds = pyhf.tensorlib.astensor([1, 0.5])
>>> values = pyhf.tensorlib.astensor([4, 9])
>>> normals = pyhf.tensorlib.normal_dist(means, stds)
>>> normals.sample((5,))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/feickert/Code/GitHub/pyhf/src/pyhf/tensor/jax_backend.py", line 29, in sample
    return norm(self.loc, self.scale).rvs(size=sample_shape + self.loc.shape)
TypeError: 'module' object is not callable
```
