### ISSUE TITLE
Inconsistent behavior of pyhf cls (opt_scipy) on lxplus vs locally

### ISSUE THREAD

**Issue by kratsg** [scikit-hep/pyhf#532]
# Description

Running `curl -sL https://git.io/fjxs5 | pyhf cls` fails on lxplus CC7 but works fine on ubuntu and on my mac. This seems to indicate probably a deeper issue with the underlying math libraries.

# Expected Behavior

CLs is computed on lxplus.

# Actual Behavior

`pyhf cls` crashes. The crash is below:

```
/afs/cern.ch/user/g/gstark/env-pyhf/lib64/python3.6/site-packages/pyhf/tensor/numpy_backend.py:184: RuntimeWarning: invalid value encountered in log
  return n * np.log(lam) - lam - gammaln(n + 1.0)
ERROR:pyhf.optimize.opt_scipy:     fun: 77.15527561970944
     jac: array([-7.08480167e+00,  8.49217033e+00,  1.47080661e+10,  3.28612328e+00,
       -7.54327774e-02, -6.71205521e-02,  5.35310745e-01,  4.01000118e+00,
       -1.52311325e-02,  1.20483060e+10,  1.16036771e+10,  1.15527170e+10,
        1.18632331e+10,  1.17691731e+10,  1.18977633e+10,  1.19250902e+10,
        1.18539326e+10,  1.48514556e+10, -1.04761124e-02, -6.01768494e-03,
       -1.34086609e-02, -2.98023224e-03,  1.56818973e+10,  6.58941269e-02,
        1.38932475e+10, -1.28894511e+02, -1.01770562e+02, -8.27344036e+00,
        1.90276623e+00, -2.19297028e+00,  1.20877792e+10,  1.05468491e+02,
        9.59411879e+01,  1.06477322e+02, -1.38329642e+02,  1.00819942e+02,
        1.26329247e+10, -9.22628508e+01, -7.78497505e+00,  1.51617641e+10,
        5.25423813e+00,  7.95975685e+00, -1.40474367e+01, -9.47475433e-03,
        9.56916809e-03, -1.23852444e+00,  6.51121140e-02, -3.54166031e-02,
       -1.73975945e-01, -6.83498383e-03, -8.06808472e-03, -9.57841873e-02,
       -3.35457802e-01,  2.93636322e-03,  1.64589882e-01, -5.11579514e-02,
        2.00636864e-01,  1.38281822e-01,  6.02092743e-02,  1.48000717e-01,
        7.17143059e-01,  4.84459877e-01, -1.01908684e-01,  7.82966614e-04,
       -7.94630051e-02,  2.16858864e-01, -1.06441498e-01,  1.34514809e-01,
        6.90739632e-01, -9.29346085e-02,  2.29740143e-02, -1.27667427e-01,
       -5.42078018e-02,  9.33218002e-02,  1.10701561e-01,  8.41569901e-02,
       -8.58306885e-06, -4.67737198e-01, -5.64012527e-02, -3.72366905e-01,
        2.63403893e-01, -7.28788376e-02,  1.74274445e-01,  2.84705162e-01,
        1.45734787e-01,  2.28877068e-01, -3.75935555e-01, -2.49648094e-01,
        2.57492065e-05, -2.14330673e-01, -3.54086399e+00, -1.08406162e+00,
        5.66859245e-01,  7.30214119e-01,  2.56684303e-01, -2.06280708e-01,
        1.26627254e+00, -3.62828255e-01,  3.13681602e-01, -4.93485451e-01,
       -9.25016403e-02,  2.30152130e-01,  1.74009991e+00, -1.03737831e-01,
        1.68754578e-01])
 message: 'Inequality constraints incompatible'
    nfev: 14765
     nit: 136
    njev: 135
  status: 4
 success: False
       x: array([ 9.99931456e-01,  1.03394352e+00, -1.07643301e-01,  1.11943363e+00,
       -3.75214605e-01, -2.93212493e-01,  1.03617837e+00,  1.00233044e+00,
        2.11720459e-01, -1.41021389e-01, -3.57913462e-02, -2.00447156e-02,
       -1.00379036e-01, -8.00860497e-02, -1.10362235e-01, -1.15776289e-01,
       -9.94856267e-02, -1.08874137e-01, -9.04132016e-02, -1.26013655e-02,
       -6.78190876e-03,  3.51948286e-03,  7.88452777e-02, -2.03839214e-01,
        8.67741934e-02, -9.57755727e-02, -6.88399120e-02, -6.02747985e-03,
        2.89433559e-03, -1.45240618e-03,  1.30866135e-01,  6.32401900e-02,
        5.41963243e-02,  7.36358010e-02, -1.05494593e-01,  7.11174277e-02,
        1.08841570e-01, -6.17440100e-02, -5.65815477e-03,  8.00748101e-02,
       -9.12257332e-02,  1.00000000e+00,  9.99795418e-01,  4.26362464e-02,
        1.73185717e-02,  9.99265203e-01, -8.28649742e-02,  2.22891209e-02,
        1.64570376e-02, -4.48735856e-03, -1.77954514e-02, -1.65394409e-01,
        9.91774213e-01,  1.01181722e+00,  1.11034657e+00, -8.75109490e-02,
        9.98451577e-01,  9.71563037e-01,  1.00550858e+00,  9.87519064e-01,
        1.00053532e+00,  9.99716238e-01,  1.00236568e+00,  1.80122396e-02,
        1.01793523e+00,  9.81009553e-01,  1.03556916e+00,  1.01505353e+00,
        9.76753479e-01,  9.94956383e-01,  1.05613511e+00,  1.04774403e+00,
        1.01198600e+00,  1.00563437e+00,  9.63984652e-02,  9.81936668e-01,
       -1.86765293e-04,  1.01079457e+00,  9.93703776e-01,  1.01142716e+00,
        1.00674961e+00,  1.00424476e+00,  1.00195613e+00,  1.01622586e+00,
        1.01148516e+00,  9.98712072e-01,  9.96932377e-01,  9.78641139e-01,
        3.82186848e-05,  1.00012172e+00,  9.98450699e-01,  9.74585427e-01,
        1.02642222e+00,  1.00512905e+00,  9.97932481e-01,  1.00604323e+00,
        1.00370171e+00,  9.97360167e-01,  9.96021892e-01,  9.98139725e-01,
        9.99044265e-01,  9.90320861e-01,  1.02224232e+00,  9.79388460e-01,
        1.02875997e+00])
Traceback (most recent call last):
  File "/afs/cern.ch/user/g/gstark/env-pyhf/bin/pyhf", line 11, in <module>
    sys.exit(pyhf())
  File "/afs/cern.ch/user/g/gstark/env-pyhf/lib64/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/afs/cern.ch/user/g/gstark/env-pyhf/lib64/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/afs/cern.ch/user/g/gstark/env-pyhf/lib64/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/afs/cern.ch/user/g/gstark/env-pyhf/lib64/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/afs/cern.ch/user/g/gstark/env-pyhf/lib64/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/afs/cern.ch/user/g/gstark/env-pyhf/lib64/python3.6/site-packages/pyhf/commandline.py", line 259, in cls
    result = hypotest(testpoi, w.data(p), p, qtilde=is_qtilde, return_expected_set=True)
  File "/afs/cern.ch/user/g/gstark/env-pyhf/lib64/python3.6/site-packages/pyhf/utils.py", line 288, in hypotest
    qmu(poi_test, asimov_data, pdf, init_pars, par_bounds), 0, max_value=None
  File "/afs/cern.ch/user/g/gstark/env-pyhf/lib64/python3.6/site-packages/pyhf/utils.py", line 113, in qmu
    loglambdav, mu, data, pdf, init_pars, par_bounds
  File "/afs/cern.ch/user/g/gstark/env-pyhf/lib64/python3.6/site-packages/pyhf/optimize/opt_scipy.py", line 43, in constrained_bestfit
    assert result.success
AssertionError
```

# Steps to Reproduce

Using the Python 3.6 distribution on LXPLUS

```
ssh $CERN_USER@lxplus.cern.ch
source scl_source enable rh-python36
python3 -m venv env-pyhf
source env-pyhf/bin/activate
pip install --upgrade pip setuptools wheel
pip install --upgrade pyhf[xmlio]
curl -sL https://git.io/fjxs5 | pyhf inspect
curl -sL https://git.io/fjxs5 | pyhf cls
```

# Checklist

- [x] Run `git fetch` to get the most up to date version of `master`
- [x] Searched through existing Issues to confirm this is not a duplicate issue
- [x] Filled out the Description, Expected Behavior, Actual Behavior, and Steps to Reproduce sections above or have edited/removed them in a way that fully describes the issue

```
$ pip list
Package        Version
-------------- -------
attrs          19.1.0 
awkward        0.12.6 
cachetools     3.1.1  
Click          7.0    
jsonpatch      1.24   
jsonpointer    2.0    
jsonschema     3.0.2  
numpy          1.17.0 
pip            18.1   
pyhf           0.1.2  
pyrsistent     0.15.4 
PyYAML         5.1.2  
scipy          1.3.1  
setuptools     40.6.2 
six            1.12.0 
tqdm           4.35.0 
uproot         3.9.0  
uproot-methods 0.7.0  
```

**Comment by matthewfeickert** [comment]
I actually get this crash on my Linux laptop as well when running off of the `master` branch install:

```
$ uname -a
Linux mcf-ThinkPad-Edge-E540 4.4.0-159-generic #187-Ubuntu SMP Thu Aug 1 16:28:06 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ curl -sL https://git.io/fjxs5 | pyhf cls
/home/mcf/Code/GitHub/pyhf/src/pyhf/tensor/numpy_backend.py:184: RuntimeWarning: invalid value encountered in log
  return n * np.log(lam) - lam - gammaln(n + 1.0)
ERROR:pyhf.optimize.opt_scipy:     fun: 77.15527561970944
     jac: array([-7.08480167e+00,  8.49217033e+00,  1.47080661e+10,  3.28612328e+00,
       -7.54327774e-02, -6.71205521e-02,  5.35310745e-01,  4.01000118e+00,
       -1.52311325e-02,  1.20483060e+10,  1.16036771e+10,  1.15527170e+10,
        1.18632331e+10,  1.17691731e+10,  1.18977633e+10,  1.19250902e+10,
        1.18539326e+10,  1.48514556e+10, -1.04761124e-02, -6.01768494e-03,
       -1.34086609e-02, -2.98023224e-03,  1.56818973e+10,  6.58941269e-02,
        1.38932475e+10, -1.28894511e+02, -1.01770562e+02, -8.27344036e+00,
        1.90276623e+00, -2.19297028e+00,  1.20877792e+10,  1.05468491e+02,
        9.59411879e+01,  1.06477322e+02, -1.38329642e+02,  1.00819942e+02,
        1.26329247e+10, -9.22628508e+01, -7.78497505e+00,  1.51617641e+10,
        5.25423813e+00,  7.95975685e+00, -1.40474367e+01, -9.47475433e-03,
        9.56916809e-03, -1.23852444e+00,  6.51121140e-02, -3.54166031e-02,
       -1.73975945e-01, -6.83498383e-03, -8.06808472e-03, -9.57841873e-02,
       -3.35457802e-01,  2.93636322e-03,  1.64589882e-01, -5.11579514e-02,
        2.00636864e-01,  1.38281822e-01,  6.02092743e-02,  1.48000717e-01,
        7.17143059e-01,  4.84459877e-01, -1.01908684e-01,  7.82966614e-04,
       -7.94630051e-02,  2.16858864e-01, -1.06441498e-01,  1.34514809e-01,
        6.90739632e-01, -9.29346085e-02,  2.29740143e-02, -1.27667427e-01,
       -5.42078018e-02,  9.33218002e-02,  1.10701561e-01,  8.41569901e-02,
       -8.58306885e-06, -4.67737198e-01, -5.64012527e-02, -3.72366905e-01,
        2.63403893e-01, -7.28788376e-02,  1.74274445e-01,  2.84705162e-01,
        1.45734787e-01,  2.28877068e-01, -3.75935555e-01, -2.49648094e-01,
        2.57492065e-05, -2.14330673e-01, -3.54086399e+00, -1.08406162e+00,
        5.66859245e-01,  7.30214119e-01,  2.56684303e-01, -2.06280708e-01,
        1.26627254e+00, -3.62828255e-01,  3.13681602e-01, -4.93485451e-01,
       -9.25016403e-02,  2.30152130e-01,  1.74009991e+00, -1.03737831e-01,
        1.68754578e-01])
 message: 'Inequality constraints incompatible'
    nfev: 14765
     nit: 136
    njev: 135
  status: 4
 success: False
       x: array([ 9.99931456e-01,  1.03394352e+00, -1.07643301e-01,  1.11943363e+00,
       -3.75214605e-01, -2.93212493e-01,  1.03617837e+00,  1.00233044e+00,
        2.11720459e-01, -1.41021389e-01, -3.57913462e-02, -2.00447156e-02,
       -1.00379036e-01, -8.00860497e-02, -1.10362235e-01, -1.15776289e-01,
       -9.94856267e-02, -1.08874137e-01, -9.04132016e-02, -1.26013655e-02,
       -6.78190876e-03,  3.51948286e-03,  7.88452777e-02, -2.03839214e-01,
        8.67741934e-02, -9.57755727e-02, -6.88399120e-02, -6.02747985e-03,
        2.89433559e-03, -1.45240618e-03,  1.30866135e-01,  6.32401900e-02,
        5.41963243e-02,  7.36358010e-02, -1.05494593e-01,  7.11174277e-02,
        1.08841570e-01, -6.17440100e-02, -5.65815477e-03,  8.00748101e-02,
       -9.12257332e-02,  1.00000000e+00,  9.99795418e-01,  4.26362464e-02,
        1.73185717e-02,  9.99265203e-01, -8.28649742e-02,  2.22891209e-02,
        1.64570376e-02, -4.48735856e-03, -1.77954514e-02, -1.65394409e-01,
        9.91774213e-01,  1.01181722e+00,  1.11034657e+00, -8.75109490e-02,
        9.98451577e-01,  9.71563037e-01,  1.00550858e+00,  9.87519064e-01,
        1.00053532e+00,  9.99716238e-01,  1.00236568e+00,  1.80122396e-02,
        1.01793523e+00,  9.81009553e-01,  1.03556916e+00,  1.01505353e+00,
        9.76753479e-01,  9.94956383e-01,  1.05613511e+00,  1.04774403e+00,
        1.01198600e+00,  1.00563437e+00,  9.63984652e-02,  9.81936668e-01,
       -1.86765293e-04,  1.01079457e+00,  9.93703776e-01,  1.01142716e+00,
        1.00674961e+00,  1.00424476e+00,  1.00195613e+00,  1.01622586e+00,
        1.01148516e+00,  9.98712072e-01,  9.96932377e-01,  9.78641139e-01,
        3.82186848e-05,  1.00012172e+00,  9.98450699e-01,  9.74585427e-01,
        1.02642222e+00,  1.00512905e+00,  9.97932481e-01,  1.00604323e+00,
        1.00370171e+00,  9.97360167e-01,  9.96021892e-01,  9.98139725e-01,
        9.99044265e-01,  9.90320861e-01,  1.02224232e+00,  9.79388460e-01,
        1.02875997e+00])
Traceback (most recent call last):
  File "/home/mcf/venvs/pyhf-dev/bin/pyhf", line 11, in <module>
    load_entry_point('pyhf', 'console_scripts', 'pyhf')()
  File "/home/mcf/venvs/pyhf-dev/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/mcf/venvs/pyhf-dev/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/mcf/venvs/pyhf-dev/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mcf/venvs/pyhf-dev/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mcf/venvs/pyhf-dev/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/mcf/Code/GitHub/pyhf/src/pyhf/commandline.py", line 259, in cls
    result = hypotest(testpoi, w.data(p), p, qtilde=is_qtilde, return_expected_set=True)
  File "/home/mcf/Code/GitHub/pyhf/src/pyhf/utils.py", line 288, in hypotest
    qmu(poi_test, asimov_data, pdf, init_pars, par_bounds), 0, max_value=None
  File "/home/mcf/Code/GitHub/pyhf/src/pyhf/utils.py", line 113, in qmu
    loglambdav, mu, data, pdf, init_pars, par_bounds
  File "/home/mcf/Code/GitHub/pyhf/src/pyhf/optimize/opt_scipy.py", line 43, in constrained_bestfit
    assert result.success
AssertionError
```

and it also fails in the Docker image we ship:

```
$ docker pull pyhf/pyhf:latest
$ docker run --rm -it pyhf/pyhf:latest
/ # apk add curl
/ # curl -sL https://git.io/fjxs5 | pyhf cls
ERROR:pyhf.optimize.opt_scipy:     fun: 78.33311774069654
     jac: array([ 1.23477936e-01,  1.24294594e+10, -7.62939453e-06, -5.22480011e-02,
        1.88527489e+00,  4.69934082e+00, -4.22093201e+00,  1.17595482e+10,
       -4.41139221e-01, -9.09616756e+00, -6.43964767e-01, -1.53725910e+00,
       -2.17113495e-02,  1.46226883e-02,  1.27659055e+10, -1.95642712e+02,
        1.15880809e+10,  1.87266350e-01,  7.12892628e+00, -1.42040253e-02,
       -9.53674316e-06,  3.30776920e+01, -1.62414551e-01,  1.25628446e+10,
        1.17164021e+10,  8.57839584e-02,  8.21352959e+00,  3.75537872e-02,
        1.15902526e+10,  3.40890884e-01,  3.36019039e+00,  1.59636784e+00,
       -3.05155754e-01,  1.79724503e+00, -3.86739731e-01,  3.65640259e+00,
       -1.13045025e+00,  1.14166164e+00, -2.01838884e+02,  4.71242905e-01,
        1.21804047e+00,  6.85165405e-01,  1.30694199e+00,  2.31633759e+00,
        1.46103477e+00, -3.36942673e-01,  1.16271973e-02, -1.07357597e+00,
        1.30253220e+00,  7.88279533e-01, -8.53385925e-01, -1.93844223e+00,
        1.18563565e+10, -3.82819366e+00, -2.15215111e+00,  2.76724815e-01,
        4.07886505e-03, -1.46389008e-02,  1.24751639e+10, -2.20950123e+02,
       -1.64437294e+00, -4.66184616e-02,  1.28683540e+10,  4.05841827e-01,
        4.23889160e-02,  8.29734802e-02,  1.61471519e+01, -1.80409672e+02,
        2.03246307e+00, -2.03937531e-01,  1.39797957e+10,  1.17003971e+10,
        1.20357213e+10,  2.28643417e-02,  1.15617746e+10, -2.89535522e-03,
        2.21162796e-01,  9.73618507e-01,  6.22305870e-01,  3.54595184e-01,
        2.05391884e-01, -1.16124058e+00, -1.59742546e+00, -1.25811768e+00,
       -1.46561050e+00, -4.96673584e-01,  1.62429810e-02,  1.26143969e+10,
        1.16619289e+10,  1.21757889e+00, -8.46718788e-01,  1.17885893e+10,
        1.21423435e+00,  1.23656465e+10,  1.33810902e+01,  7.61890411e-03,
        1.10454559e-02,  2.04391479e-02, -2.88370132e-01,  1.37509727e+00,
        2.50603867e+01,  1.16933114e+10, -2.35516262e+01, -5.04346848e-01,
        1.70707703e-03])
 message: 'Inequality constraints incompatible'
    nfev: 11859
     nit: 108
    njev: 108
  status: 4
 success: False
       x: array([-2.75423028e-01,  8.82603280e-02, -4.79684558e-04,  2.10659587e-01,
        1.01181794e+00,  9.99903194e-01,  9.99262402e-01, -1.36233169e-01,
        9.87552197e-01,  9.75342782e-01,  9.91302439e-01,  1.00735950e+00,
        1.10261276e+00,  1.01819823e+00, -1.22787277e-01, -1.09957985e-01,
       -7.69288223e-02,  1.00341295e+00, -4.83785706e-02, -9.49380825e-03,
        1.49551154e-04,  9.99979892e-01,  9.77436457e-02,  8.13558116e-02,
       -1.20713678e-01, -2.68766515e-01,  1.12035676e+00,  2.64730852e-02,
       -7.64455363e-02,  1.01392440e+00,  1.00867574e+00,  1.00635907e+00,
        1.00154097e+00,  1.01850723e+00,  1.00865974e+00,  1.00191534e+00,
        9.96236000e-01,  1.00091362e+00, -1.14541015e-01,  9.96512678e-01,
        1.00772838e+00,  1.00336929e+00,  1.00093369e+00,  1.00043400e+00,
        9.79476768e-01,  1.02612528e+00,  1.00331322e+00,  9.95974323e-01,
        1.00938780e+00,  1.00357313e+00,  9.95830409e-01,  1.01656814e+00,
        1.27734036e-01, -1.93998238e-03, -1.18638867e-03, -3.90021831e-02,
        1.92466593e-02, -7.00113028e-03,  8.65624142e-02, -1.17167435e-01,
        9.67362942e-01, -2.92489877e-03, -1.30092767e-01,  1.00002508e+00,
        9.98096774e-01,  1.00396144e+00,  9.88205938e-03, -9.07013472e-02,
        1.00221617e+00,  4.42055205e-02,  5.46571665e-02, -1.16362988e-01,
        1.12813045e-01, -5.89810363e-02, -6.51304950e-02, -1.13052042e-01,
        4.41135117e-02,  9.87951544e-01,  1.04295711e+00,  1.01728929e+00,
        9.74082934e-01,  9.92072404e-01,  1.04212600e+00,  1.03588133e+00,
        9.98166335e-01,  1.00292302e+00,  5.47077801e-02,  8.50018576e-02,
       -1.01401083e-01,  1.01156501e+00,  9.58944486e-01,  1.31865257e-01,
        1.03130933e+00,  9.12552713e-02,  8.04457139e-01,  9.58822028e-03,
       -2.05733919e-01,  1.87715502e-03, -1.25778602e-01,  1.03513328e+00,
        1.03513744e+00, -1.14376686e-01, -1.29159627e-02,  9.88373739e-01,
        9.70427146e-01])
Traceback (most recent call last):
  File "/usr/bin/pyhf", line 11, in <module>
    load_entry_point('pyhf', 'console_scripts', 'pyhf')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/code/src/pyhf/commandline.py", line 259, in cls
    result = hypotest(testpoi, w.data(p), p, qtilde=is_qtilde, return_expected_set=True)
  File "/code/src/pyhf/utils.py", line 288, in hypotest
    qmu(poi_test, asimov_data, pdf, init_pars, par_bounds), 0, max_value=None
  File "/code/src/pyhf/utils.py", line 116, in qmu
    loglambdav, data, pdf, init_pars, par_bounds
  File "/code/src/pyhf/optimize/opt_scipy.py", line 22, in unconstrained_bestfit
    assert result.success
AssertionError
```

**Comment by matthewfeickert** [comment]
and it also fails in my Ubuntu 18.04 image with Python 3.7.4

```
$docker pull matthewfeickert/docker-python3-ubuntu:3.7.4
$ docker run --rm -it matthewfeickert/docker-python3-ubuntu:3.7.4
# Inside the container
$ uname -a
Linux 8c2ae249a9e1 4.4.0-159-generic #187-Ubuntu SMP Thu Aug 1 16:28:06 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ python --version
Python 3.7.4
$ pip --version
pip 19.2.1 from /usr/lib/python3.7/site-packages/pip (python 3.7)
$ pip install --user pyhf[xmlio]
$ curl -sL https://git.io/fjxs5 | pyhf cls
/home/docker/.local/lib/python3.7/site-packages/pyhf/tensor/numpy_backend.py:184: RuntimeWarning: invalid value encountered in log
  return n * np.log(lam) - lam - gammaln(n + 1.0)
ERROR:pyhf.optimize.opt_scipy:     fun: 77.15527561970944
     jac: array([-7.08480167e+00,  8.49217033e+00,  1.47080661e+10,  3.28612328e+00,
       -7.54327774e-02, -6.71205521e-02,  5.35310745e-01,  4.01000118e+00,
       -1.52311325e-02,  1.20483060e+10,  1.16036771e+10,  1.15527170e+10,
        1.18632331e+10,  1.17691731e+10,  1.18977633e+10,  1.19250902e+10,
        1.18539326e+10,  1.48514556e+10, -1.04761124e-02, -6.01768494e-03,
       -1.34086609e-02, -2.98023224e-03,  1.56818973e+10,  6.58941269e-02,
        1.38932475e+10, -1.28894511e+02, -1.01770562e+02, -8.27344036e+00,
        1.90276623e+00, -2.19297028e+00,  1.20877792e+10,  1.05468491e+02,
        9.59411879e+01,  1.06477322e+02, -1.38329642e+02,  1.00819942e+02,
        1.26329247e+10, -9.22628508e+01, -7.78497505e+00,  1.51617641e+10,
        5.25423813e+00,  7.95975685e+00, -1.40474367e+01, -9.47475433e-03,
        9.56916809e-03, -1.23852444e+00,  6.51121140e-02, -3.54166031e-02,
       -1.73975945e-01, -6.83498383e-03, -8.06808472e-03, -9.57841873e-02,
       -3.35457802e-01,  2.93636322e-03,  1.64589882e-01, -5.11579514e-02,
        2.00636864e-01,  1.38281822e-01,  6.02092743e-02,  1.48000717e-01,
        7.17143059e-01,  4.84459877e-01, -1.01908684e-01,  7.82966614e-04,
       -7.94630051e-02,  2.16858864e-01, -1.06441498e-01,  1.34514809e-01,
        6.90739632e-01, -9.29346085e-02,  2.29740143e-02, -1.27667427e-01,
       -5.42078018e-02,  9.33218002e-02,  1.10701561e-01,  8.41569901e-02,
       -8.58306885e-06, -4.67737198e-01, -5.64012527e-02, -3.72366905e-01,
        2.63403893e-01, -7.28788376e-02,  1.74274445e-01,  2.84705162e-01,
        1.45734787e-01,  2.28877068e-01, -3.75935555e-01, -2.49648094e-01,
        2.57492065e-05, -2.14330673e-01, -3.54086399e+00, -1.08406162e+00,
        5.66859245e-01,  7.30214119e-01,  2.56684303e-01, -2.06280708e-01,
        1.26627254e+00, -3.62828255e-01,  3.13681602e-01, -4.93485451e-01,
       -9.25016403e-02,  2.30152130e-01,  1.74009991e+00, -1.03737831e-01,
        1.68754578e-01])
 message: 'Inequality constraints incompatible'
    nfev: 14765
     nit: 136
    njev: 135
  status: 4
 success: False
       x: array([ 9.99931456e-01,  1.03394352e+00, -1.07643301e-01,  1.11943363e+00,
       -3.75214605e-01, -2.93212493e-01,  1.03617837e+00,  1.00233044e+00,
        2.11720459e-01, -1.41021389e-01, -3.57913462e-02, -2.00447156e-02,
       -1.00379036e-01, -8.00860497e-02, -1.10362235e-01, -1.15776289e-01,
       -9.94856267e-02, -1.08874137e-01, -9.04132016e-02, -1.26013655e-02,
       -6.78190876e-03,  3.51948286e-03,  7.88452777e-02, -2.03839214e-01,
        8.67741934e-02, -9.57755727e-02, -6.88399120e-02, -6.02747985e-03,
        2.89433559e-03, -1.45240618e-03,  1.30866135e-01,  6.32401900e-02,
        5.41963243e-02,  7.36358010e-02, -1.05494593e-01,  7.11174277e-02,
        1.08841570e-01, -6.17440100e-02, -5.65815477e-03,  8.00748101e-02,
       -9.12257332e-02,  1.00000000e+00,  9.99795418e-01,  4.26362464e-02,
        1.73185717e-02,  9.99265203e-01, -8.28649742e-02,  2.22891209e-02,
        1.64570376e-02, -4.48735856e-03, -1.77954514e-02, -1.65394409e-01,
        9.91774213e-01,  1.01181722e+00,  1.11034657e+00, -8.75109490e-02,
        9.98451577e-01,  9.71563037e-01,  1.00550858e+00,  9.87519064e-01,
        1.00053532e+00,  9.99716238e-01,  1.00236568e+00,  1.80122396e-02,
        1.01793523e+00,  9.81009553e-01,  1.03556916e+00,  1.01505353e+00,
        9.76753479e-01,  9.94956383e-01,  1.05613511e+00,  1.04774403e+00,
        1.01198600e+00,  1.00563437e+00,  9.63984652e-02,  9.81936668e-01,
       -1.86765293e-04,  1.01079457e+00,  9.93703776e-01,  1.01142716e+00,
        1.00674961e+00,  1.00424476e+00,  1.00195613e+00,  1.01622586e+00,
        1.01148516e+00,  9.98712072e-01,  9.96932377e-01,  9.78641139e-01,
        3.82186848e-05,  1.00012172e+00,  9.98450699e-01,  9.74585427e-01,
        1.02642222e+00,  1.00512905e+00,  9.97932481e-01,  1.00604323e+00,
        1.00370171e+00,  9.97360167e-01,  9.96021892e-01,  9.98139725e-01,
        9.99044265e-01,  9.90320861e-01,  1.02224232e+00,  9.79388460e-01,
        1.02875997e+00])
Traceback (most recent call last):
  File "/home/docker/.local/bin/pyhf", line 10, in <module>
    sys.exit(pyhf())
  File "/home/docker/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/docker/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/docker/.local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/docker/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/docker/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/docker/.local/lib/python3.7/site-packages/pyhf/commandline.py", line 259, in cls
    result = hypotest(testpoi, w.data(p), p, qtilde=is_qtilde, return_expected_set=True)
  File "/home/docker/.local/lib/python3.7/site-packages/pyhf/utils.py", line 288, in hypotest
    qmu(poi_test, asimov_data, pdf, init_pars, par_bounds), 0, max_value=None
  File "/home/docker/.local/lib/python3.7/site-packages/pyhf/utils.py", line 113, in qmu
    loglambdav, mu, data, pdf, init_pars, par_bounds
  File "/home/docker/.local/lib/python3.7/site-packages/pyhf/optimize/opt_scipy.py", line 43, in constrained_bestfit
    assert result.success
AssertionError
```

**Comment by kratsg** [comment]
Further debug has the subproblems converging (except for the 3rd)

```
Optimization terminated successfully.    (Exit mode 0)
            Current function value: 114.21281626391162
            Iterations: 204
            Function evaluations: 22071
            Gradient evaluations: 204
Optimization terminated successfully.    (Exit mode 0)
            Current function value: 101.96132355405202
            Iterations: 219
            Function evaluations: 23720
            Gradient evaluations: 219
Inequality constraints incompatible    (Exit mode 4)
            Current function value: 77.15527561970944
            Iterations: 136
            Function evaluations: 14765
            Gradient evaluations: 135
```

**Comment by lukasheinrich** [comment]
does MINUIT  work?

**Comment by kratsg** [comment]
minuit does not work, CLs_exp=1, CLs_obs=NaN

**Comment by lrnv** [comment]
Hi,

If i understand correctly the thread here : http://scipy-user.10969.n7.nabble.com/SciPy-User-optimize-fmin-slsqp-bounds-problem-td18779.html the problem might come directly from the SLSQP fortran code, and is there since a few years now... Sadly i have no capabilities of reading fortran !

The issue is that the "Inequality constraints incompatible" message is misleading : several unclear conditions seems to return an exit mode 4, without all of them being clearly related to incompatibility in the constraints.

**Comment by kratsg** [comment]
This does not crash anymore on lxplus (cc7).
