### ISSUE TITLE
Fix TensorFlow v2.3.0 and TensorFlow Probability v0.11.0 release incompatibilities

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#997]
# Description

[TensorFlow `v2.3.0`](https://github.com/tensorflow/tensorflow/releases/tag/v2.3.0) has been released today (2020-07-27) but is breaking the tests in CI with the following:

```
    pythonLocation: /opt/hostedtoolcache/Python/3.7.8/x64
2020-07-27 21:25:53.025362: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-07-27 21:25:53.025414: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
ImportError while loading conftest '/home/runner/work/pyhf/pyhf/tests/conftest.py'.
tests/conftest.py:83: in <module>
    (pyhf.tensor.tensorflow_backend(), None),
src/pyhf/tensor/__init__.py:50: in __getattr__
    e,
E   pyhf.exceptions.ImportBackendError: ('There was a problem importing TensorFlow. The tensorflow backend cannot be used.', ImportError("cannot import name 'naming' from 'tensorflow.python.autograph.core' (/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/tensorflow/python/autograph/core/__init__.py)"))
##[error]Process completed with exit code 4.
```

the code snippet that is being reported here is:

https://github.com/scikit-hep/pyhf/blob/60488cd4223dcc5519605b766db1f9af91fa79fb/src/pyhf/tensor/__init__.py#L39-L51

but the actual error is

```
2020-07-27 21:25:53.025362: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
```

as with TensorFlow `v2.3.0` just importing gets you the attempt to load `libcudart.so.10.1`

```python
>>> import tensorflow as tf
2020-07-27 16:40:48.374806: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
```

# Expected Behavior

The test suite runs

# Actual Behavior

c.f. above

# Steps to Reproduce

Run the CI.

# Checklist

- [x] Run `git fetch` to get the most up to date version of `master`
- [x] Searched through existing Issues to confirm this is not a duplicate issue
- [x] Filled out the Description, Expected Behavior, Actual Behavior, and Steps to Reproduce sections above or have edited/removed them in a way that fully describes the issue

**Comment by matthewfeickert** [comment]
Though this might be something that we need to catch as just trying to import `tensorflow` (`python -c "import tensorflow as tf"`) after the dependencies are installed gives

```
2020-07-27 21:51:18.905311: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-07-27 21:51:18.905345: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
```

**Comment by matthewfeickert** [comment]
@kratsg has pointed out that this is actually a problem with TensorFlow Probability `v0.10.X` releases as `v0.11.X` uses TF `v2.3.X`.

```
$ docker run --rm -it python:3.8-slim /bin/bash
# pip install pyhf[tensorflow]
# pip list | grep tensor
tensorboard            2.3.0
tensorboard-plugin-wit 1.7.0
tensorflow             2.3.0
tensorflow-estimator   2.3.0
tensorflow-probability 0.10.1
# python
Python 3.8.2 (default, Apr 23 2020, 14:32:57) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyhf
>>> pyhf.set_backend("tensorflow")
2020-07-27 23:16:40.268209: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-07-27 23:16:40.268358: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyhf/tensor/__init__.py", line 41, in __getattr__
    from .tensorflow_backend import tensorflow_backend
  File "/usr/local/lib/python3.8/site-packages/pyhf/tensor/tensorflow_backend.py", line 4, in <module>
    import tensorflow_probability as tfp
  File "/usr/local/lib/python3.8/site-packages/tensorflow_probability/__init__.py", line 76, in <module>
    from tensorflow_probability.python import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python3.8/site-packages/tensorflow_probability/python/__init__.py", line 24, in <module>
    from tensorflow_probability.python import experimental
  File "/usr/local/lib/python3.8/site-packages/tensorflow_probability/python/experimental/__init__.py", line 34, in <module>
    from tensorflow_probability.python.experimental import auto_batching
  File "/usr/local/lib/python3.8/site-packages/tensorflow_probability/python/experimental/auto_batching/__init__.py", line 24, in <module>
    from tensorflow_probability.python.experimental.auto_batching import frontend
  File "/usr/local/lib/python3.8/site-packages/tensorflow_probability/python/experimental/auto_batching/frontend.py", line 45, in <module>
    from tensorflow.python.autograph.core import naming
ImportError: cannot import name 'naming' from 'tensorflow.python.autograph.core' (/usr/local/lib/python3.8/site-packages/tensorflow/python/autograph/core/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/pyhf/events.py", line 68, in register_wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pyhf/__init__.py", line 88, in set_backend
    backend = getattr(tensor, f"{backend:s}_backend")(**backend_kwargs)
  File "/usr/local/lib/python3.8/site-packages/pyhf/tensor/__init__.py", line 48, in __getattr__
    raise exceptions.ImportBackendError(
pyhf.exceptions.ImportBackendError: ('There was a problem importing TensorFlow. The tensorflow backend cannot be used.', ImportError("cannot import name 'naming' from 'tensorflow.python.autograph.core' (/usr/local/lib/python3.8/site-packages/tensorflow/python/autograph/core/__init__.py)"))
>>>
# pip install --upgrade "tensorflow-probability>=v0.11.0-rc1"
# pip list | grep tensor
tensorboard            2.3.0
tensorboard-plugin-wit 1.7.0
tensorflow             2.3.0
tensorflow-estimator   2.3.0
tensorflow-probability 0.11.0rc1
# python
Python 3.8.2 (default, Apr 23 2020, 14:32:57) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyhf
>>> pyhf.set_backend("tensorflow")
2020-07-27 23:18:06.709873: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-07-27 23:18:06.709903: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
>>> 
```

**Comment by matthewfeickert** [comment]
Some good news on the issues RE: SciPy and TF `v2.3.0` and TFP `v0.11.0` seen in PR #1001: https://groups.google.com/a/tensorflow.org/forum/?utm_medium=email&utm_source=footer#!topic/discuss/wLRLe96ymFg

TF `v2.4.0` "is slated to come out sometime around september/october." and a patch release of `v2.3.X` might be possible. :+1: Thanks to @alextp for being super responsive too.

**Comment by matthewfeickert** [comment]
Further related to PR #1001 are https://github.com/tensorflow/tensorflow/pull/41867 and https://github.com/tensorflow/tensorflow/issues/41902. I've gone ahead and subscribed to these so that we can keep tabs on them and act quickly.

**Comment by alexander-held** [comment]
What is the status of this? [`TensorFlow` 2.5.0](https://github.com/tensorflow/tensorflow/releases/tag/v2.5.0) is available now, so maybe some of the above issues are resolved. I am looking into this as I was hoping to find a setup with `pyhf` that allows testing the `TensorFlow` backend but also to use `numpy`>=1.20 for typing reasons (reference: https://github.com/alexander-held/cabinetry/pull/228). Installing `TensorFlow` 2.5.0 picks up `numpy~=1.19.2`, so it seems like this unfortunately may not be possible yet.
